### ISSUE TITLE
Parsing APIs

### ISSUE THREAD

**Issue by jzaefferer** [tc39/ecma402#1]
Currently the spec has no APIs for parsing dates or numbers. Supposedly the response used to be "use a datepicker" when asking about date parsing. I'm wondering if that changed.

**Comment by srl295** [comment]
@jzaefferer I think the main issues may be:
* triaging for the 1st edition.
* parsing is not usually 1:1 (unlike format) therefore 
 * parsing can require control of [leniency](http://www.icu-project.org/apiref/icu4c/classicu_1_1DateFormat.html#a5ed3fc3977aabeae6b0188642cad5d30) 

In any event, I think that, unlike the way ICU does it with a symmetric object (input+output), it would be better to have a separate object for parsing.

**Comment by zbraniecki** [comment]
I agree with @srl295. Parsing dates especially feels like a very risky task with extremely high barrier for good user experience. Unless we can provide something that works for 95% cases, developers who will decide to use it will have to manually parse it anyway for when Intl API fails, and will probably come up with their own solution anyway. I'd leave it to specialized libraries.

**Comment by caridy** [comment]
Closing this issue by consensus, but if anyone wants to go for it, we are open to evaluate the concrete proposal.

**Comment by jungshik** [comment]
JFYI,  v8 has v8Parse, but we may get rid of it soon pending the stat collection on it usage. 

/cc @littledan, @cira, @jungshik
