### ISSUE TITLE
Canonicalize "Etc/UCT" to "UTC" in CanonicalizeTimeZoneName?

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#121]
As currently spec'ed, CanonicalizeTimeZoneName doesn't canonicalize "Etc/UCT" to "UTC", because "Etc/UCT" is a separate zone in tzdata. Is this intentional?

**Comment by zbraniecki** [comment]
@littledan, @caridy, @jungshik ?

**Comment by littledan** [comment]
FWIW Chrome and Firefox reject creating a DateTimeFormat with this timezone.

What's the purpose of this time zone? How should it be handled? Is there any chance it could change in the future (in which case it's presumably good that we are not canonicalizing them together)? Are there other programming environments that canonicalize them together?

**Comment by anba** [comment]
> FWIW Chrome and Firefox reject creating a DateTimeFormat with this timezone.

Support for time zones is only available in Firefox Nightly. 

> What's the purpose of this time zone?

AFAIU it's just a different name for UTC. According to [this post](https://mm.icann.org/pipermail/tz/2014-June/021022.html), it's only present as distinct zone because it's abbreviation is different from "UTC". And given that we're already canonicalizing "Etc/GMT" to "UTC", we should probably also canonicalize "Etc/UCT" to "UTC".

**Comment by littledan** [comment]
Well, it seems to me that the tz database is the right place to decide on these things; I don't see a compelling reason for us to jump in.

**Comment by anba** [comment]
Also: In ICU-based Intl implementations, the formatted output string from Intl.DateTimeFormat.p.format uses the abbreviation "GMT" for all three time zones (Etc/UTC, Etc/UCT, and Etc/GMT).

**Comment by maggiepint** [comment]
I'm not sure if you should be canonicalizing anything from GMT to UTC. If you read a little further down the TZDB thread, they made the explicit choice to NOT do this, so people could have their choice of abbreviation. If someone uses "Etc/UCT", one would assume the abbreviation they want is UCT. Same for GMT and UTC.

For what it's worth, I would not expect the TZDB to change decisions about this in the future.

@mj1856 is the person who started TZDB thread, don't know if he wants to have an opinion here.

**Comment by mj1856** [comment]
While the [official answer](http://mm.icann.org/pipermail/tz/2014-June/021022.html) from the TZDB was that GMT, UTC, and UCT are distinct so that they can have different abbreviations, I'll also point out that CLDR *does* map them all to GMT - which explains @anba's point about ICU-based implementations.

CLDR's [bcp47/timezone.xml](http://unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml) shows the data as follow:

```xml
<type name="utc" description="UTC (Coordinated Universal Time)" alias="Etc/UTC Etc/UCT Etc/Universal Etc/Zulu UCT UTC Universal Zulu"/>
```

Personally, I prefer `UTC` over `GMT`, and I believe `UCT` shouldn't be used at all.

**Comment by littledan** [comment]
Oh, I see. Maybe we should permit referencing CLDR rather than normatively referencing the TZ database here. This case is analogous to https://github.com/tc39/ecma402/issues/134 which could also be addressed similarly, by either permitting a CLDR reference or just being vague about the source of information (as much of the spec is already).

**Comment by littledan** [comment]
Cross-browser comparison given the timezone 'UCT':
- SpiderMonkey canonicalizes to 'Etc/UCT'
- V8 rejects UCT because it doesn't have a slash
- JSC canonicalizes to 'UTC'

*shrug emoji*

**Comment by caridy** [comment]
I'm not sure how to proceed here, but we definitely need the buy-in from Microsoft with respect to referencing CLDR from the spec, and I'm still waiting from @bterlson on that.

This definitely worth the effort since we have different behavior in different browsers at the moment.

**Comment by bterlson** [comment]
I hope to give the green light on normative CLDR references in time for the meeting next week!

**Comment by jungshik** [comment]
> Also: In ICU-based Intl implementations, the formatted output string from Intl.DateTimeFormat.p.format uses the abbreviation "GMT" for all three time zones (Etc/UTC, Etc/UCT, and Etc/GMT).

I think that is locale-dependent. en-US uses GMT, but de  uses UTC and fr uses UCT, IIRC. 

Anyway, another recent CLDR change is to make Etc/UTC distinct from Etc/GMT (even though their behavior is identical). See http://unicode.org/cldr/trac/ticket/9943 and a Chrome change to take that into account and be compliant to Ecma 402 (https://chromium-review.googlesource.com/c/496406/4 )

**Comment by jungshik** [comment]
>  In ICU-based Intl implementations, the formatted output string from Intl.DateTimeFormat.p.format uses the abbreviation "GMT" for all three time zones (Etc/UTC, Etc/UCT, and Etc/GMT).

And, with the above CLDR change I referred to, the formatting output for Etc/GMT is now different from that for Etc/UTC.  I have to check which pair has the same formatting output, {Etc/GMT, Etc/UCT} or {Etc/UTC, Etc/UCT}.

**Comment by jungshik** [comment]
> I think that is locale-dependent. en-US uses GMT, but de uses UTC and fr uses UCT, IIRC.

Oops. Current, CLDR data has UTC for only 'fi', 'fr' and 'se'. And, for most of other locales, it's GMT. (a few locales have localized name - ar, si, am, bg, dz, fa, ga, km, ml, sq).  I don't like "GMT" :-)  I wish it's 'UTC' in all the locales.

**Comment by mj1856** [comment]
@jungshik, I don't think we're talking about the localized name, just the aliases in bcp47/timezone.xml.

Yes, I saw CLDR split out UTC from GMT.  They did, however, keep UCT as an alias for UTC.

**Comment by littledan** [comment]
What do you all think? Should we allow or require this canonicalization?

**Comment by mj1856** [comment]
For `Etc/UCT`, my vote would be to treat it the same as `Etc/UTC` and `Etc/GMT` - canonicalize it to `UTC`.

Curious though, how do we expect implementations to produced locale-specific strings for UTC when that is not in CLDR?  (See http://unicode.org/cldr/trac/ticket/8252)

Also, from earlier:
> - V8 rejects UCT because it doesn't have a slash

I just noticed that it's rejecting many valid zones, even with a slash.  For example, `US/Pacific` and `Etc/GMT-2`.  It would appear V8 is accepting only the subset of tzdb identifiers that are in the full `Area/Locality` form.  That's concerning, as the older style is still abundant in the wild.  I think this is already addressed in the 402 spec, in 6.4, "Implementations must recognize all such names", so I'd say that V8 is not compliant at the moment.

In general, I would expect any `Zone` or `Link` entry to work in 402 that are found in one of these files of the tzdb: `africa`, `antarctica`, `asia`, `australasia`, `backward`, `etcetera`, `europe`, `northamerica`, `southamerica`.  The other files are either related to tzcode, or are for special cases.

Note that `Link` entries are found throughout these files - they are not *all* in `backward`, so the spec should be updated for that in 6.4.2(2).

**Comment by anba** [comment]
Looks like this issue will resolve itself with the next tzdata update: https://github.com/eggert/tz/commit/ce0baf7a4955c0942ea0c6a182bf94a961237fbc

**Comment by rxaviers** [comment]
> Curious though, how do we expect implementations to produced locale-specific strings for UTC when that is not in CLDR? (See http://unicode.org/cldr/trac/ticket/8252)

Do you mean this data ([en](https://github.com/unicode-cldr/cldr-dates-full/blob/dc94116e7e43e5f8df76615108124716a32c5e89/main/en/timeZoneNames.json#L1337), [es](https://github.com/unicode-cldr/cldr-dates-full/blob/dc94116e7e43e5f8df76615108124716a32c5e89/main/es/timeZoneNames.json#L1336), [pt](https://github.com/unicode-cldr/cldr-dates-full/blob/dc94116e7e43e5f8df76615108124716a32c5e89/main/pt/timeZoneNames.json#L1336), ...)? If so, perhaps the CLDR trac bug (4 years old) needs to be updated.

**Comment by littledan** [comment]
Great work, @isiahmeadows @eggert . Closing this issue as the proper upstream fix is on the way--very glad we don't have to do anything special at our level.
