### ISSUE TITLE
Change InitializeCollator and InitializeNumberFormat to use default options which don't inherit from %ObjectPrototype%

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#123]
InitializeCollator and InitializeNumberFormat currently use `ObjectCreate(%ObjectPrototype%)` to create the default options object. For consistency with InitializeDateTimeFormat (through ToDateTimeOptions) and to enable the common browser fast-paths for Number.prototype.toLocaleString and String.prototype.localeCompare, we should consider changing InitializeCollator and InitializeNumberFormat to use  `ObjectCreate(null)`.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1296233 for why the browser fast paths for Number.prototype.toLocaleString and String.prototype.localeCompare aren't spec-compliant.

**Comment by zbraniecki** [comment]
@caridy, @littledan, @jungshik ?

**Comment by littledan** [comment]
V8 has the exact same bug described there. The issue invalidates our use of a cache for number of Intl-related implementations; I'd imagine we share issues with `String.prototype.localeCompare()` as well.

I think WebIDL has behavior for dictionaries similar to what @anba is proposing for Intl options.

WebIDL dictionaries are used for options bags in Web APIs, among other things. You can see the same option resolution scenario written out in the [ES value to WebIDL dictionary conversion algorithm](https://heycam.github.io/webidl/#es-dictionary), that if the ES value is `undefined`, then it will become the default value for fields with a default, or be "missing" for fields that are not specified, but never go back and look at `Object.prototype`.

All together, I'm strongly in support of this change.

cc @domenic @annevk for WebIDL expertise.

**Comment by annevk** [comment]
Ideally JavaScript/IDL use a shared algorithm for this, but perhaps that's out-of-scope for this issue.

**Comment by domenic** [comment]
After reading through this I don't quite understand the issue. Web IDL does indeed look at Object.prototype, since it just does a `Get(options, "propName")`. Only if that comes back as undefined will it fall back to the default/missing. See: http://jsbin.com/figopifeji/edit?html,console,output

**Comment by littledan** [comment]
@domenic This is for the case where the options are missing.

**Comment by domenic** [comment]
I see, then yes, Object.prototype is not consulted then.

**Comment by littledan** [comment]
Seems like something related is being done in https://github.com/tc39/ecma402/pull/157/commits/18edad7ef54db152dca10bb30e088eece10169a2 . I think this is a good idea in general.

**Comment by littledan** [comment]
Spec patch: https://github.com/tc39/ecma402/pull/170

Test262 tests: https://github.com/tc39/test262/pull/1220

Experimental implementation: https://chromium-review.googlesource.com/c/v8/v8/+/657839
