### ISSUE TITLE
time components if UTC and time zone is known

### ISSUE THREAD

**Issue by bsr203** [tc39/ecma402#125]
I have asked a question at SO, and seems like no way to do this.

I could format a UTC time in any timezone using `Intl.DateTimeFormat`, irrespective of user browser locale. Instead of string representation, is there a way to get parts (hours, minutes, etc which is aware of the timezone. see the original question below.

thanks.

--
http://stackoverflow.com/questions/41993989/time-components-if-utc-and-time-zone-is-known

I have a date time picker, which uses getHours, getMinutes,.. to initialize the value. It works well if timezone coincide with user location, but I want to consider the case where user tz is different than the current browser locale setting. I can use Intl.DateTimeFormat to correctly format the date into another timezone. But, I want to get the time component values (hour, minute,..) of say "America/Chicago" while my local time is "America/New_York". That is I need to get time as 17 if I set offset as "America/Chicago", irrespective of current local timezone . Is this possible without using moment.js, or any better way to do this.

https://jsfiddle.net/zhvx6mmt/1/

```
const baseUTCDate = new Date(Date.UTC(2017, 2, 1, 23, 0, 0));
function formatDate(date, timeZone, locale) {
  const options = { weekday: 'long', year: 'numeric', month: 'short',
    day: 'numeric', hour: 'numeric', minute: 'numeric', timeZoneName: 'short' };
  return new Intl.DateTimeFormat(locale, Object.assign(options, {timeZone: timeZone})).format(date);
}

console.log(formatDate(baseUTCDate, "America/New_York",  'en-US')) 
// Wednesday, Mar 1, 2017, 6:00 PM EST

console.log(formatDate(baseUTCDate, "America/Chicago",  'en-US'))
// Wednesday, Mar 1, 2017, 5:00 PM CST

console.log(baseUTCDate.getHours()) // 18 - local time zone is EST
```

**Comment by littledan** [comment]
Unfortunately, the built-in JavaScript libraries are not currently well-suited to this task. We've been talking in TC39 about improving the libraries, but we don't have a concrete proposal yet--hopefully it'll come soon. Until then, you can use user-based libraries like moment.js for this task. cc @bterlson @maggiepint

I think this can issue be closed.

**Comment by bsr203** [comment]
Thank you for the detailed response. Hopefully the builtin functionality would improve to avoid depending on external libraries.
