### ISSUE TITLE
Normative Optional steps need prose

### ISSUE THREAD

**Issue by allenwb** [tc39/ecma402#129]
There doesn't appear to be any explanation or guidance for implementations on the purpose of the various "normative optional" steps throughout the specification. Contract this to [clause B.3](https://tc39.github.io/ecma262/#sec-other-additional-features) of ECMA-262 which generally has some text explaining why each "normally optional" feature exists.

When I read the algorithms and see such steps, I have no idea why they exist and what they are trying to accomplished

A bit of prose on for each occurrence would be helpful. 

Also, I assume that implementation should either implement all such "normative optional" steps throughout the spec. or none of them.  But I don't think that is actually stated anywhere.

**Comment by littledan** [comment]
Do you think notes explaining motivation are more important for normative optional parts of the spec than other parts? I think motivation and history is always great to document, and I like the idea of documenting it in the spec (though hopefully it can be done in one place, rather than four, somehow), but I don't see how Annex B differs.

**Comment by allenwb** [comment]
We, in 262 Annex B, we say stuff like:

>Prior to ECMAScript 2015, the specification of _LabelledStatement_ did not allow for the association of a statement label with a _FunctionDeclaration_. However, a labelled _FunctionDeclaration_ was an allowable extension for non-strict code and most browser-hosted ECMAScript implementations supported that extension. 

It would be nice to have a comparable statement  about the purpose of the the normative optional code in ECMA-402.

I think the inlining of these steps also changes their understandability as there isn't a single place to find such an explanation.  Perhaps we should have an "Annex B" that juara gives an explanation of each normatively optional feature.  Then the individual algorithms that have normatively optional steps could just reference the approbate "Annex B" section for the explanation.

**Comment by littledan** [comment]
I like this idea. Should we also consider documenting the motivation for things that are not normative-optional, or is it better to keep that sort of documentation outside of the main spec text?

**Comment by allenwb** [comment]
Well, one of the roles of informative notes is to provide a place for this sort of information.  I think it makes sense to document non-obvious motivations or explanations using such notes. We just need to be careful that they don't include material that should be normative.
