### ISSUE TITLE
Should we really be reading {minimum,maximum}SignificantDigits twice?

### ISSUE THREAD

**Issue by littledan** [tc39/ecma402#131]
It looks like, in [SetNumberFormatDigitOptions](https://tc39.github.io/ecma402/#sec-setnfdigitoptions), if either one returns something other than **undefined** for the first Get call, we do a *second* Get to get the real value that we use (from inside GetNumberOption). Is there a reason for this, besides that it was easier to write the spec that way? It would seem more straightforward if we just stuck with the value from the first time we read it out of the object.

**Comment by caridy** [comment]
You're correct, that code is not necessary since `GetNumberOption()` will return undefined for undefined values.

**Comment by littledan** [comment]
I'm confused; won't `GetNumberOption` return the fallback if the value resulting from `Get` is `undefined`? It seems like this change you made will break the logic.
