### ISSUE TITLE
Rebuild the copy in tc39.github.io/ecma402

### ISSUE THREAD

**Issue by littledan** [tc39/ecma402#142]
The current rendered copy seems a bit outdated; for example, it doesn't include the PR at 0b8ca359a5e09826db72bcc89a98e0fc68a3533e which has been merged for a couple weeks. Maybe ECMA 402 would benefit from porting @bterlson 's Travis-CI configuration that ECMA262 has to automate deployment.

**Comment by mathiasbynens** [comment]
Similar configuration is already in place. However, it seems something is causing the deployment to fail: https://travis-ci.org/tc39/ecma402/builds/213590578#L276
