### ISSUE TITLE
toLocaleString() narrow: non-unique values

### ISSUE THREAD

**Issue by drzraf** [tc39/ecma402#146]
Nothing in the spec' ensure that the one-letter "narrow" value of weekday (from Date.toLocaleString()) is **unique**.

As a consequence:
* ``new Date("2017-05-16T16:00:00").toLocaleString('fr', {weekday:'narrow'});``
M (for "_mardi_")
* ``new Date("2017-05-17T16:00:00").toLocaleString('fr', {weekday:'narrow'});``
M (for "_mercredi_")

apply to Chromium 57 and Firefox 45

**Comment by drzraf** [comment]
Worthy asking what, in the spec', ensure that values are going to be consistent among browsers implementations.

**Comment by zbraniecki** [comment]
At this point, I think it's worth reporting as a CLDR bug - http://www.unicode.org/cldr/charts/31/summary/fr.html#1875 and 1876

**Comment by drzraf** [comment]
done. thx for the pointer.

BTW browsers use the "abbreviated" output (unicode semantics) when using
the "short" argument (ecma402 semantics)

**Comment by drzraf** [comment]
http://unicode.org/cldr/trac/ticket/10301

**Comment by caridy** [comment]
closing this in favor of the CLDR ticket.

**Comment by drzraf** [comment]
Answer of unicode.org: "Work as-designed" :
> We document that these names do not need to be distinct, they are intended to be used in contexts where they are all shown together so that it is obvious which one is which. See ​http://www.unicode.org/reports/tr35/tr35-dates.html#Calendar_Elements

Worth being reopened here then

**Comment by drzraf** [comment]
ping @caridy

**Comment by jungshik** [comment]
No need to reopen. Spec doesn't say so because cannot be guaranteed for all locales.  Where narrow is typically used(e.g. monthly calendar), it is not necessary either.

**Comment by jungshik** [comment]
The cldr answer you got is also applied here.

**Comment by drzraf** [comment]
Specs can (must?) _guarantee_ whatever seems sane for the purpose they have.

Classifying this `not a bug` or `not our bug` simply makes `toLocaleString('fr', {weekday:'narrow'});` useless in all but one case:  when the user can visually differentiate the meaning of the letter from the context (ex: calendar columns showing all letters in an ordered manner like in `L M M J V S D` or  `M T W T F S S`).

Every other uses I can think of would create confusions for the user or program or both.
I'd prefer to see ECMA 402 stricter w.r.t. this so that `narrow` can be useful.

For the record:
```
es:  L M X J V S D  (conflict:false)
en:  M T W T F S S  (conflict:true)
de:  M D M D F S S  (conflict:true)
fr:  L M M J V S D  (conflict:true)
sv:  M T O T F L S  (conflict:true)
el:  Δ Τ Τ Π Π Σ Κ  (conflict:true)
za:  M T W T F S S  (conflict:true)
pl:  P W Ś C P S N  (conflict:true)
sk:  p u s š p s n  (conflict:true)
cs:  P Ú S Č P S N  (conflict:true)
da:  M T O T F L S  (conflict:true)
tk:  M T W T F S S  (conflict:true)
zh:  一 二 三 四 五 六 日  (conflict:false)
he:  ב׳ ג׳ ד׳ ה׳ ו׳ ש׳ א׳  (conflict:false)
ja:  月 火 水 木 金 土 日  (conflict:false)
pa:  ਸੋ ਮੰ ਬੁੱ ਵੀ ਸ਼ੁੱ ਸ਼ ਐ  (conflict:true)
```

**Comment by rxaviers** [comment]
@drzraf, you should use at least `"short"` for unique values.

**Comment by jungshik** [comment]
> when the user can visually differentiate the meaning of the letter from the context (ex: calendar columns showing all letters in an ordered manner like in L M M J V S D or M T W T F S S).

That's exactly 'narrow' is for.

**Comment by caridy** [comment]
To add to @jungshik comment, if you want unique values, use "short":

```
new Date("2017-05-17T16:00:00").toLocaleString('fr', {weekday:'short'});
"mer."
new Date("2017-05-16T16:00:00").toLocaleString('fr', {weekday:'short'});
"mar."
```

**Comment by drzraf** [comment]
My application use weekdays in it's internal state and they are represented in the URL, eg: `filter=<day1><dayN>...` (concatenation of one-byte symbols of weekdays)

I went into MSDN documentation to see which *standard* format would fit my need (other than numeric) rather than reinventing an index.
I wanted a shorter representation than _short_ since being multi-byte create useless complexity (seven items could technically be represented using one byte each without problem)
But I needed a `guaranteed to be unique` one-byte identifier. Having `filter=lmm` is not suitable.

Numeric numbers of day in the week? Well I'd have liked that `getDay()` would respect ISO 8601 spec's about weekdays the way `toLocaleString` respects Unicode spec's "narrow" non-uniqueness semantic ;)
Numeric as "simple", short and *unique* identifier for week-days is as [simple](https://stackoverflow.com/questions/14270281/does-getday-comply-with-iso-8601#comment19811126_14270380) as using `(getDay() + 6) % 7 + 1`
Alternative option being using Spanish (an anonymous common-sensed man made it the unique mainstream language having conflict-free _narrow_ symbol set)

Side note: if these symbols are unsuitable for programs and only intended visually for users, then they could be changed without expecting a compatibility-break since program are either broken in the first place or already containing hacks to workaround duplicated symbols.

/me going with (numerical) .`getDay()`

**Comment by littledan** [comment]
For representing data in a URL, Intl APIs are definitely not recommended. Seems like you've found a workable solution with `getDay()`. For an all-around cleanup of the Date API, see [the temporal proposal](https://github.com/tc39/proposal-temporal). cc @maggiepint
