### ISSUE TITLE
NumberFormat.prototype.parse method

### ISSUE THREAD

**Issue by everdimension** [tc39/ecma402#147]
Had anyone thought that it might be very useful to have a `NumberFormat.prototype.parse` which does the opposite of `format`?

It can be very useful to know how a certain formatted number can be parsed since in different locales different symbols (such as decimal marks) can have different meaning.

So for example:

```javascript
new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY' }).format(123456.789)
// '￥123,457'

new Intl.NumberFormat('ja-JP').parse('￥123,457')
// would return something like { currency: 'JPY', value: 123457 }
```

**Comment by littledan** [comment]
See related issue at https://github.com/tc39/ecma402/issues/1 .
