### ISSUE TITLE
`hourCycle` option is resolved twice during InitializeDateTimeFormat

### ISSUE THREAD

**Issue by zbraniecki** [tc39/ecma402#162]
With the merge of @anba patch, we now resolve `GetOption(options, "hourCycle")` twice - as step 8 and as step 29.

@anba - is that what you intended or is it a merge bug from @caridy ?

**Comment by anba** [comment]
> @anba - is that what you intended or is it a merge bug from @caridy ?

It's a merge issue, the second `GetOption` for "hourCycle" should be removed.

And related: These [three lines](https://github.com/tc39/ecma402/pull/155/files#diff-1f2e1333fe08618e8af2d7344b031dc1R122) should be reinserted. (And I just saw, I've missed a full stop after `Set _hc_ to _hcDefault_`.)

**Comment by caridy** [comment]
ha! auto-merging and conflict resolutions, my bad. Do you want to send a PR @anba ?

**Comment by zbraniecki** [comment]
@caridy @anba - can you please fix it? :)
