### ISSUE TITLE
NumberFormat: new option to force sign

### ISSUE THREAD

**Issue by ray007** [tc39/ecma402#163]
`Intl.NumberFormat` could use an option to also show a sign (`"+"`) for positive numbers.

**Comment by caridy** [comment]
We need to format proposal, and a champion :)

**Comment by ray007** [comment]
- It may not be needed often, but some of our customer have asked for it. I missed it for formatting ISO8601 timezone offsets.
- I don't think you'd want this always on, but I don't know enough about most locales to judge that.
- It's defined in `main/{localeId}/numbers.json`, key `symbols-numberSystem-latn/plusSign`

**Comment by anba** [comment]
Now possible through the `"signDisplay"` option:
```js
js> print(new Intl.NumberFormat('en', { signDisplay: "always" }).format(10))                                                
+10
```

**Comment by sffc** [comment]
Yep, the proposal is Stage 4 and merged.  Closing as Fixed
