### ISSUE TITLE
Editorial: Update Array.prototype.toLocaleString's algorithm to ECMA-262's style modulo material differences

### ISSUE THREAD

**Issue by dilijev** [tc39/ecma402#173]
Updating the algorithm would remove confusion about the differences between the two and fix errors.

Since the difference is minor, add a note specifying that the only difference is the additional `« locales, options »` argument to `Invoke(nextElement, "toLocaleString")`.

See below for more details.

262:

```
1. Let array be ? ToObject(this value).
2. Let len be ? ToLength(? Get(array, "length")).
3. Let separator be the String value for the list-separator String appropriate for the host environment's current locale (this is derived in an implementation-defined way).
4. Let R be the empty String.
5. Let k be 0.
6. Repeat, while k < len
    a. If k > 0, then
        i. Set R to the string-concatenation of R and separator.
    b. Let nextElement be ? Get(array, ! ToString(k)).
    c. If nextElement is not undefined or null, then
        i. Let S be ? ToString(? Invoke(nextElement, "toLocaleString")).
        ii. Set R to the string-concatenation of R and S.
    d. Increase k by 1.
7. Return R.
```

402:

```
1. Let array be ? ToObject(this value).
2. Let len be ? ToLength(? Get(array, "length")).
3. Let separator be the String value for the list-separator String appropriate for the host environment’s current locale (this is derived in an implementation-defined way).
4. If len is zero, return the empty String.
5. Let firstElement be ? Get(array, "0").
6. If firstElement is undefined or null, then
    a. Let R be the empty String.
7. Else,
    a. Let R be ? ToString(? Invoke(firstElement, "toLocaleString", « locales, options »)).
8. Let k be 1.
9. Repeat, while k < len
    a. Let S be a String value produced by concatenating R and separator.
    b. Let nextElement be ? Get(array, ToString(k)).
    c. If nextElement is undefined or null, then
        i. Let R be the empty String.
    d. Else,
        ii. Let R be ? ToString(? Invoke(nextElement, "toLocaleString", « locales, options »)).
    e. Let R be a String value produced by concatenating S and R.
    f. Increase k by 1.
10. Return R.
```

I believe there are some errors in 402's version. Otherwise, these algorithms appear to have been intended as isomorphisms to each other, modulo the additional `« locales, options »` argument to `Invoke` in 402.

402's `? Get(array, ToString(k))` is missing a `!` before `ToString` as is present in 262's version: `? Get(array, ! ToString(k))`

The handling of the special case for index 0 (not adding a separator before the first element) was handled more elegantly in 262's version (hence the shorter length of the algorithm).

Note that 262's version has a reference to the dfn string-concatenation (`Set R to the string-concatenation of R and S.`) whereas 402 says: `Let R be a String value produced by concatenating S and R.`.

In 402's version:

```
8. Let k be 1.
9. Repeat, while k < len
...
    c. If nextElement is undefined or null, then
        i. Let R be the empty String.
```

9.c. would mean when we see undefined or null then we restart with an empty string. This is clearly an error in copy-paste from step 6. This is correct in 262's version.

/cc @jmdyck

**Comment by anba** [comment]
> The handling of the special case for index 0 (not adding a separator before the first element) was handled more elegantly in 262's version (hence the shorter length of the algorithm).

https://github.com/tc39/ecma262/pull/662 updated the 262 algorithm to handle the first element in the loop.

> 9.c. would mean when we see undefined or null then we restart with an empty string. This is clearly an error in copy-paste from step 6. This is correct in 262's version.

Step 9.a saves the current string in _S_, so this actually okay.

**Comment by dilijev** [comment]
> Step 9.a saves the current string in S, so this actually okay.

Ah, I missed that. Thanks.

Still think we should bring 402's definition up to be in line with 262's.
