### ISSUE TITLE
Should IsStructurallyValidLanguageTag ban grandfathered/irregular/extlang tags?

### ISSUE THREAD

**Issue by littledan** [tc39/ecma402#177]
These are supported by [RFC 5646](https://tools.ietf.org/html/rfc5646#section-2.1) but [explicitly skipped over](http://www.unicode.org/reports/tr35/#BCP_47_Conformance) in UTS 35's defintion of "Unicode locale identifiers".

**Comment by jungshik** [comment]
I wonder what value we provide by supporting those tags.  

We can also take a middle road;  namely support those grandfathered tags with preferred values but ban those without preferred values. 

See also https://bugs.chromium.org/p/v8/issues/detail?id=7669#c10 .

**Comment by jungshik** [comment]
Perhaps, banning altogether is cleaner than deviating from both RFC 5646 and UTS 35 by taking a middle road?

**Comment by anba** [comment]
Only regular grandfathered tags are still accepted, the rest is no longer valid since the change to use "Unicode BCP 47 locale identifiers".

**Comment by littledan** [comment]
Yes, I'm closing this issue as we've resolved the open questions by adopting Unicode BCP 47 locale identifiers.
