### ISSUE TITLE
Create an "npm update-pages" (like ecmascript-asyncawait has)

### ISSUE THREAD

**Issue by rwaldron** [tc39/ecma402#18]
https://github.com/tc39/ecmascript-asyncawait/blob/master/package.json#L31-L33

**Comment by rwaldron** [comment]
Or https://github.com/tc39/Array.prototype.includes/blob/master/deploy.sh

**Comment by caridy** [comment]
Aligned with 262:

```
npm run update-pages
git push origin gh-pages
```
