### ISSUE TITLE
Should we update "Numbering systems with simple digit mappings" for newer CLDR/Unicode versions?

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#183]
https://tc39.github.io/ecma402/#table-numbering-system-digits is currently limited to the numbering systems defined in CLDR21 which are representable with Unicode 5.0 compatible characters. Does it makes sense to update this table and require more numbering systems?

**Comment by littledan** [comment]
If we have this table, it should be kept up to date. I'm wondering, though, how much value it adds to maintain this, as opposed to just defer to implementations. cc @NorbertLindenberg

**Comment by sffc** [comment]
This was fixed by @FrankYFTang in #437.
