### ISSUE TITLE
Update String.prototype.toLocaleLowerCase / toLocaleUpperCase to mirror recent updates for toLowerCase/toUpperCase

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#184]
See https://github.com/tc39/ecma262/issues/254 and https://github.com/tc39/ecma262/pull/932

**Comment by caridy** [comment]
@littledan do you plan to work on this?

**Comment by spectranaut** [comment]
Fixed in: https://github.com/tc39/ecma402/pull/341
