### ISSUE TITLE
Intentional? : Different handling of NaN, Infinity by Date.toLocaleString and Intl.DateTimeFormat

### ISSUE THREAD

**Issue by jungshik** [tc39/ecma402#187]
Date.toLocaleString() and Intl.DateTimeFormat handle NaN and Infinity differently.  The former returns 'Invalid Date' while the latter throws RangeError.  Given that they have different purposes, the current difference is likely to be intentional. 

However, there's another difference ('Not a finite Number' vs 'NaN'. ).  This one needs to be consistent. 

I think that [#sup-date.prototype.tolocalestring](https://www.ecma-international.org/ecma-402/4.0/index.html#sup-date.prototype.tolocalestring) should also check for 'Not a finite Number' instead of just 'NaN'. That way, 'Infinity' and '-Infinity' would be handled the same way as 'NaN'. If we make this change in Ecma 402, the corresponding section on Date.to{Time,Date,}String has to be revised as well. 

[#sec-partitiondatetimepattern](https://www.ecma-international.org/ecma-402/4.0/index.html#sec-partitiondatetimepattern) has this:

```
If x is not a finite Number, throw a RangeError exception.
```

OTOH, [#sup-date.prototype.tolocalestring](https://www.ecma-international.org/ecma-402/4.0/index.html#sup-date.prototype.tolocalestring) has this. It's the same as Date.toString() in Ecma 402. 

```
This definition supersedes the definition provided in ES2017, 20.3.4.39.

When the toLocaleString method is called with optional arguments locales and options, the following steps are taken:

Let x be ? thisTimeValue(this value).
If x is NaN, return "Invalid Date".
```

**Comment by jungshik** [comment]
@littledan

**Comment by anba** [comment]
The value returned by ` thisTimeValue` doesn't contain infinities, cf. https://tc39.github.io/ecma262/#sec-time-values-and-time-range, so the current checks look okay to me.

**Comment by anba** [comment]
TimeClip seems to be missing in PartitionDateTimePattern, so I've just filed #192 to track that issue.

**Comment by littledan** [comment]
I agree with @anba 's reading about toLocaleString, and suggested an alternative fix for the other issue [in a comment on his PR](https://github.com/tc39/ecma402/pull/194#issuecomment-340428440).

**Comment by littledan** [comment]
Is this addressed by https://github.com/tc39/ecma402/pull/194 ?

**Comment by jungshik** [comment]
I think so. Let's close this.
