### ISSUE TITLE
Apply TimeClip in PartitionDateTimePattern?

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#192]
https://tc39.github.io/ecma402/#sec-partitiondatetimepattern states:
> [...] interprets x as a time value as specified in ES2015, 20.3.1.1 [...]

but PartitionDateTimePattern doesn't actually apply [20.3.1.15 TimeClip](https://tc39.github.io/ecma262/#sec-timeclip) to ensure `x` is a valid time value. So I think we should apply the following change to PartitionDateTimePattern:

```diff
- 1. If x is not a finite Number, throw a RangeError exception.
+ 1. Let x be TimeClip(x).
+ 2. If x is NaN, throw a RangeError exception.
```

**Comment by caridy** [comment]
Yes, I think using `TimeClip` here is accurate, I wasn't aware of that indirection. Do you plan to send a PR @anba?
