### ISSUE TITLE
Don't escape object JSON when not converter to string.

### ISSUE THREAD

**Issue by renanbastos93** [tc39/ecma402#199]
Hey guys, 

I communicate that when we go use the `escape` to object JSON it don't escape correctly.
So I think we should add this suggestion.

```js
const obj2 = {"name": "NodeJS", "version": "all"};
console.log(escape(obj)); //%5Bobject%20Object%5D
```
It  needs to do this:
```js
const obj = {"name": "NodeJS", "version": "all"};
console.log(escape(obj)); //%7B%22name%22%3A%22NodeJS%22%2C%22version%22%3A%22all%22%7D
```
As this we will reduce a step to escape.

Wthat's you think about? 
I make myself available to do this.

**Comment by mathiasbynens** [comment]
`escape(JSON.stringify(obj))` gives you the output you want.

**Comment by renanbastos93** [comment]
I know, but I suggestion this to have more facility and optimization one code.

What do you think?

**Comment by caridy** [comment]
@renanbastos93 this question is not related to ecma-402, probably es-discuss or ecma-262.
