### ISSUE TITLE
ECMA 402 phone meeting

### ISSUE THREAD

**Issue by littledan** [tc39/ecma402#202]
Would you be interested in joining a regular call to discuss the specification development of Intl? How about an initial call on December 15th at 18:00 UTC, for one hour? cc @zbraniecki @caridy @jungshik @ericf @rxaviers @sffc @bterlson @msaboff @mathiasbynens @jswalden @anba @jasnell @nciric @stasm @srl295 @eemeli

Rationale:
- A lot of people interested in ECMA 402 can't make it to physical TC39 meetings.
- Many TC39 members are not interested in all the details of Intl development.
- TC39 Intl proposals have to share time with non-Intl proposals, and in the end there isn't enough time for either in meeting agendas.
- It's often hard to get everyone's feedback on GitHub bug threads.

Details:
- In these meetings, we could go over interesting ECMA 402 bugs, PRs,
and any of the outstanding proposals to make progress on.
- Meetings would be open to any TC39 member or invited expert guest.
- Strawman schedule: Once a month, on the second Thursday of the month, at 17:00 UTC (modulo any adjustments for conflicts) for one hour.
- We can use the meetings come to decisions on issues, split up work items among us, review spec proposals and recommend stage advancement to TC39.
- Technically, we could be a new Task Group of TC39, but I think it would be OK to start out informal and unchartered.

What do you think?

**Comment by bterlson** [comment]
I would attend. FYI: @dilijev @jackhorton

**Comment by nciric** [comment]
I would attend.

**Comment by zbraniecki** [comment]
I cannot attend at the proposed time. I can do the 13th, or 15th or preferably any day in the week after that.

**Comment by dilijev** [comment]
I would attend.

**Comment by littledan** [comment]
I've made a doodle to figure out which time we're all free to meet:

https://doodle.com/poll/s9f363z62xs85dte

**Comment by littledan** [comment]
Note that the times in the above doodle are in UTC.

**Comment by bterlson** [comment]
uhoh, when I get a chance I'll have to redo my responses... thanks for calling that out @littledan

**Comment by nciric** [comment]
California is now in PST, so 18h UTC should be 10AM local (if internet doesn't lie :))

**Comment by mimckenna** [comment]
Anyone mind if I join in to listen in and get caught up on status and issues of ECM-402 intl?  I won't enter in the doodle to skew the results 😼

**Comment by littledan** [comment]
Please come @mimckenna ! Apologies for leaving you out of cc earlier, and don't feel shy about filling out the doodle. I will send everyone an email with the hangouts link once we determine the time.

**Comment by srl295** [comment]
doodle has a time zone option IIRC

**Comment by bterlson** [comment]
FWIW I updated my availability.

**Comment by stasm** [comment]
Thanks for proposing this, @littledan! I'd love to attend.

**Comment by littledan** [comment]
OK, thanks for writing into the doodle, to everyone who did so promptly. Let's meet on Friday, December 15th and 18:00 UTC. I will follow up with an agenda proposal in this repository and a calendar invite. One small issue: I don't have Shane Carr's email address. Could someone send it to me, at littledan-at-igalia-dot-com?

**Comment by littledan** [comment]
OK, found an email address for everyone who responded to the doodle and sent an invitation. If anyone else would like to be invited, please let me know here.

**Comment by jackhorton** [comment]
I should be able to join at that time. My email is jahorto@microsoft.com. Thanks!

**Comment by littledan** [comment]
Sent an invitation to @jackhorton . @mimckenna , what is your email address?

**Comment by eemeli** [comment]
I should be able to make it, please send me an invite as well.

**Comment by littledan** [comment]
@eemeli Sent

**Comment by littledan** [comment]
I wrote an agenda which you can find at https://github.com/tc39/ecma402/blob/master/meetings/agenda-2017-12-15.md . If you have any other ideas for what you'd like to cover (or not cover), please make a PR against the agenda or let me know.

**Comment by zbraniecki** [comment]
Closing this as the monthly meeting took off!
