### ISSUE TITLE
UTS35 vs BCP47 nomenclature issue for [[Calendar]]

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#212]
From #175:

---

https://tc39.github.io/ecma402/#sec-properties-of-intl-datetimeformat-instances describes [[Calendar]] as:

>  [[Calendar]] is a String value with the "type" given in Unicode Technical Standard 35 for the calendar used for formatting.

But which "type" is meant here? The value of the "name" attribute of the <type> element for BCP 47 (https://unicode.org/repos/cldr/tags/latest/common/bcp47/calendar.xml) or the value of "type" attribute of the <calendar> element (https://unicode.org/repos/cldr/tags/latest/common/main/root.xml)? [...]

For example `Intl.DateTimeFormat("de-u-ca-gregory").resolvedOptions().calendar` prints "gregory" for me with V8 and SpiderMonkey, but "gregorian" with JSC (on Ubuntu16.04, IIRC JSC uses the system ICU which is ICU55 for Ubuntu16.04; V8 and SpiderMonkey both use ICU60). Right now I'd say only JSC is correct here and "gregorian" is the expected output. [...]

---

But in the current spec the BCP47 calendar type is used ("gregory" appears four times in the 402 spec, whereas "gregorian" is not mentioned at all).

**Comment by srl295** [comment]
it should be the bcp47 (actually, U extension) type, which is also specified within TR35, with a note that this may differ from the cldr type.

**Comment by sffc** [comment]
I think it would be smart for us to put a list of supported calendars into ECMA-402.  We should obey the BCP 47 syntax, including "gregory" for the Gregorian calendar.

**Comment by littledan** [comment]
We've now standardized on UTS 35 locale normalization, which makes it clear that aliases are substituted by canonical values. (This is independent of whether we require actual support for the calendar.) Does this resolve the issue?

**Comment by sffc** [comment]
JSC now prints "gregory" here, consistent with the other browsers.  I'll close this issue; please reopen if there is any further work.
