### ISSUE TITLE
PartitionNumberPattern treats -0 as 0

### ISSUE THREAD

**Issue by jackhorton** [tc39/ecma402#219]
```
1. If x is not NaN and x < 0, then
    a. Let x be -x.
    b. Let pattern be numberFormat.[[NegativePattern]].
2. Else,
    a. Let pattern be numberFormat.[[PositivePattern]].
```

Unfortunately, -0 === 0, so -0 uses numberFormat.[[PositivePattern]]. I have confirmed that both SpiderMonkey ~59 and ChakraCore ~1.10 currently format -0 in "en-US" as "0"

**Comment by littledan** [comment]
I agree that -0 should be handled differently. Would you be interested in writing a spec patch and test262 tests to change -0 to use the NegativePattern path?

**Comment by anba** [comment]
Maybe PartitionNumberPattern intentionally handles -0 as +0 for consistency with `Number.prototype.toString`?

**Comment by jackhorton** [comment]
There was discussion [in IRC](http://logs.libuv.org/tc39/2018-02-27) that this wouldn't be natively supported by ICU right now, so any test that I add would probably fail on any ICU implementation. I can look into it this week though!

**Comment by littledan** [comment]
@jackhorton File an ICU ticket? cc @srl295

**Comment by jackhorton** [comment]
There were a handful listed in IRC, it looked like support wouldn't be coming to NumberFormat but might be coming to NumberFormatter soon.

1. http://bugs.icu-project.org/trac/ticket/12936
1. http://bugs.icu-project.org/trac/ticket/13551
1. http://bugs.icu-project.org/trac/ticket/8333

**Comment by anba** [comment]
ICU4C and ICU4J both print "-0" for -0, verified by removing 

https://searchfox.org/mozilla-central/rev/14d933246211b02f5be21d2e730a57cf087c6606/js/src/builtin/intl/NumberFormat.cpp#374-376
resp.
https://github.com/anba/es6draft/blob/7e196e8a1482384ca83946998f5fbd22068b47c6/src/main/java/com/github/anba/es6draft/runtime/objects/intl/NumberFormatConstructor.java#L403-L406

and the calling `(-0).toLocaleString()`. Also the following test262 test will then fail:
https://github.com/tc39/test262/blob/master/test/intl402/NumberFormat/prototype/format/format-negative-numbers.js

**Comment by srl295** [comment]
@sffc can you clarify?

**Comment by sffc** [comment]
ICU4C and ICU4J will print "-0" if given the Double -0.0.

I have no strong opinion on what the ECMA 402 behavior should be, but as others have said, it would be nice to be consistent with `Number.prototype.toString`.

**Comment by littledan** [comment]
The built-in `toString()` methods are weird in a lot of ways. If we have a more linguistically useful answer for our formatters, I think we shouldn't take `toString()` as a very strong precedent.

**Comment by littledan** [comment]
We discussed this issue in the [April 2018 Intl call](https://github.com/littledan/ecma402/blob/notes/meetings/notes-2018-04-20.md) and it sounded like there was agreement on making this change. I put up a quick PR at https://github.com/tc39/ecma402/pull/232 ; is this what others are imagining? Does anyone want to put together an implementation to try this out, and tweak the test262 test @anba mentioned above?

**Comment by ajklein** [comment]
Sorry to comment on a closed issue, but I was just made aware of this as V8 is being updated to match the spec.

What I don't see here is a motivation for this change. My mental model of these APIs is for use to display to users, and it seems unlikely to me that we ever want to show users "-0" instead of "0".

Can someone provide further background on this?

**Comment by sffc** [comment]
Another comment on -0 vs 0.  Seems to be a topic many people have an opinion on. :)

The decision on separating -0 and 0 in Intl was made in the April Intl call; littledan linked to the notes.  Several people expressed opinions there.  I can only speak for myself, but here are some reasons why I supported treating -0 and 0 differently:

1. We are more correctly reflecting the nature of JavaScript's Number type, which supports -0.
2. If you don't like the behavior, it is trivial to work around in user code, but this is not the case in the other direction where a user wants the sign on -0 but we don't give them a way to do it.
3. It's not too hard to think of potential use cases.  Here's one: suppose you are showing the change in stock price over time, rounded to the nearest integer.  You might write "-0%" when the actual difference is something else small like -0.1%.

Here are some more threads where people have expressed opinions on -0:

- https://github.com/tc39/proposal-unified-intl-numberformat/issues/23
- https://github.com/tc39/proposal-unified-intl-numberformat/pull/25
- https://github.com/tc39/proposal-unified-intl-numberformat/issues/13

**Comment by littledan** [comment]
Does this issue need to be reopened?

**Comment by ajklein** [comment]
(1) and (2) don't sway me very much, so it really comes down to (3). For this rounding case, it could _also_ be handled in user code if desired, so it comes down to the default.

I don't know if this needs re-opening, but my input is basically: this was surprising to me, and I think the arguments for changing it aren't stronger than the arguments against.

**Comment by zbraniecki** [comment]
From the intl perspective the distinction between `-0` and `0` is significant because in many languages it results in different grammatical cases, declensions etc.
I'd prefer if an intl API did not enforce `0==-0` and as others pointed out, coalescing this distinction is easier than cleanly separating out in the userland.

**Comment by ajklein** [comment]
I can understand the distinction between, say, `1` and `-1`, for grammatical purposes. But outside of floating point math, where does `-0` show up in natural language? That's really my central confusion here.

**Comment by zbraniecki** [comment]
https://en.wikipedia.org/wiki/Signed_zero#Scientific_uses

```
Informally, one may use the notation "−0" for a negative value that was rounded to zero. This notation may be useful when a negative sign is significant; for example, when tabulating Celsius temperatures, where a negative sign means below freezing. 
```

In particular, this API is used to allow for styling, and styling of negative vs. positive numbers is a common scenario.
