### ISSUE TITLE
Legacy constructor semantics need to ensure the this-value is an object

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#222]
The semantics of this test case are currently not defined, because it calls the DefinePropertyOrThrow abstract operation on a non-Object value.

```js
Object.defineProperty(Intl.NumberFormat, Symbol.hasInstance, { value: () => true });
(0, Intl.NumberFormat)();
```

**Comment by anba** [comment]
#418 has a fix for this issue (<https://github.com/tc39/ecma402/pull/418/commits/dcfa23d455bf20462c5c57f76f0285d13f93ab59>).

**Comment by littledan** [comment]
#418 has landed, so I take it this is fixed.
