### ISSUE TITLE
Why does ResolveLocale drop Unicode extension keys without values?

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#223]
```js
var opt1 = new Intl.Collator("de-u-kn").resolvedOptions();
var opt2 = new Intl.Collator("de-u-kn-true").resolvedOptions();

print(`locale=${opt1.locale}, caseFirst=${opt1.numeric}`);
print(`locale=${opt2.locale}, caseFirst=${opt2.numeric}`);
```

The test case should print this per the current spec:
```
locale=de, caseFirst=true
locale=de-u-kn-true, caseFirst=true
```

I don't understand why the resolved locale of the first collator is not set to either `de-u-kn` or `de-u-kn-true`. If the current behaviour is not a spec bug, can we add a comment to clarify why Unicode extensions keys without values are removed from the resolved locale?

**Comment by littledan** [comment]
Huh, that's interesting.

Would fixing this be a matter of adding a simple step as ResolveLocale 8.h.ii.2.b Let _supportedExtensionAddition_ be the concatenation of "-" and _key_ ? If so, that sort of change sounds right to me.

(Aside: Wow, there's a lot of variation among implementations for how the locale presents these tags.)

**Comment by srl295** [comment]
> `caseFirst=${opt1.numeric}`

should be `numeric=`?

**Comment by littledan** [comment]
Rather than just making this one fix (which, in isolation, would seem good), let's see if we can make this part of [a broader change](https://github.com/tc39/proposal-intl-locale/issues/31).
