### ISSUE TITLE
Copy [[PluralCategories]] in Intl.PluralRules.prototype.resolvedOptions?

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#224]
Follow-up from https://github.com/tc39/proposal-intl-plural-rules/issues/28#issuecomment-341557030

Seems like I've misinterpreted the SpiderMonkey implementation, because SpiderMonkey definitely returns a copy of the `[[PluralCategories]]` array in `Intl.PluralRules.prototype.resolvedOptions()`:  https://searchfox.org/mozilla-central/rev/6e96a3f1e44e286ddae5fdafab737709741d237a/js/src/builtin/intl/PluralRules.js#235-240

**Comment by littledan** [comment]
I thought we settled on not copying the array. Sorry if I didn't document this clearly in bug threads, but reviewing that thread, it looks like we settled on not copying there. Do we want to reconsider this decision? @caridy @zbraniecki @thejoshwolfe

**Comment by zbraniecki** [comment]
I don't have a strong opinion here.

**Comment by anba** [comment]
> I thought we settled on not copying the array.

Well, I thought SM didn't copy the array (https://github.com/tc39/proposal-intl-plural-rules/issues/28#issuecomment-342546687), but actually SM does the copy the array and it did so since day one. That's why I wanted to discuss this issue again. And always returning a new array is consistent with how `resolvedOptions()` works in general, that is it always returns a new object.

**Comment by littledan** [comment]
I'd recommend not copying, per the resolution in https://github.com/tc39/proposal-intl-plural-rules/issues/28 , and we can pursue a specification change separately if you want to make the case for it. If there are no test262 tests that verify not copying, then it'd be great if someone added one.

**Comment by littledan** [comment]
We discussed this in the [April 2018 Intl call](https://github.com/littledan/ecma402/blob/notes/meetings/notes-2018-04-20.md) and the conclusion was to always do the copying.

**Comment by littledan** [comment]
Drafted spec text for this change at https://github.com/tc39/ecma402/pull/233 . Does anyone want to create test262 tests to verify?
