### ISSUE TITLE
Handling unexpected ICU field IDs

### ISSUE THREAD

**Issue by littledan** [tc39/ecma402#231]
I recently learned that ICU users are supposed to be able to handle unexpected values from iterating over fields. Many ECMA-402 implementations are on top of ICU. I can see a few ways to handle this case:
1. Crash with an assertion failure (V8's strategy, apparently incorrect)
1. Leave out that range in formatToParts (but, this risks not actually presenting the whole string)
1. Choose another string for the type

Choice 3 seems the best to me, especially since these assertion failures [are starting to come up in practice](https://bugs.chromium.org/p/chromium/issues/detail?id=826549). Is `"literal"` is the type we want there? Or should we somehow permit a new type, such as `"unknown"`, for these cases?

**Comment by jungshik** [comment]
Thank you, @littledan , for filing this issue.  I've been thinking along the line of the 3rd choice as well. Perhaps, 'unknown' ?

**Comment by jackhorton** [comment]
I vote for `"literal"` on unmapped types, personally.

**Comment by littledan** [comment]
We [discussed](https://github.com/tc39/ecma402/blob/master/meetings/notes-2018-05-17.md) this question in the May 2018 Intl meeting, and came to the conclusion to use "unknown" for these sorts of cases. Does anyone want to make a patch to the specification for this change? (I'm not sure exactly how to write it, actually...)
