### ISSUE TITLE
Iteration order not specific enough

### ISSUE THREAD

**Issue by gsathya** [tc39/ecma402#264]
In [InitializeDateTimeFormat](https://tc39.github.io/ecma402/#sec-initializedatetimeformat):

> 22. For each row of Table 5, except the header row, do

In [Intl.PluralRules.prototype.resolvedOptions](https://tc39.github.io/ecma402/#sec-intl.pluralrules.prototype.resolvedoptions):

> 8. For each row of Table 8, except the header row, do

In all other cases, the spec defines the iteration order.

cc @FrankYFTang

**Comment by jungshik** [comment]
In what context does the order matter for DateTimeFormat?  v8 constructs a format skeleton and passes it to ICU's [DateTimePatternGenerator::getBestPattern(skeleton)]( https://cs.chromium.org/chromium/src/third_party/icu/source/i18n/unicode/dtptngen.h?rcl=a191af9d025859e8368b8b469120d78006e9f5f6&l=320).  

The spec tries to describe what ICU does and the above ICU API is order-agnostic. That is, 'yMd',  'Myd', or 'dMy' is supposed to return the same bestfit pattern available for a given locale.

**Comment by gsathya** [comment]
> In what context does the order matter for DateTimeFormat?

I don't think it's particularly useful, but the subsequent `GetOption` call is observable to JavaScript, which means the order in which the table is iterated is visible to JavaScript. 

ECMA262 exactly specifies all ordering that is visible to JavaScript. It'd be great to do the same here.

**Comment by littledan** [comment]
Agree that the order is significant. My understanding of the meaning of this spec text was that "for each" is implicitly strictly in table order here. If it would be clearer to make this explicit, as in some instances in the spec, let's make that change.
