### ISSUE TITLE
Add a note to Intl.NumberFormat.prototype.format

### ISSUE THREAD

**Issue by Ms2ger** [tc39/ecma402#265]
Intl.DateTimeFormat.prototype.format has a note:

> The returned function is bound to _dtf_ so that it can be passed directly to **`Array.prototype.map`** or other functions.

Intl.NumberFormat.prototype.format should probably have something similar.

**Comment by littledan** [comment]
I guess, or we could delete both notes. At this point, I believe we are considering this binding to be a mistake.

**Comment by Ms2ger** [comment]
I agree it's a mistake, but unless we're going to remove it entirely, we should have a note about why it was made in the first place.

**Comment by littledan** [comment]
Sure, PRs welcome.
