### ISSUE TITLE
Real-time communication channel

### ISSUE THREAD

**Issue by littledan** [tc39/ecma402#268]
Should we use Slack or IRC for a chat room to talk about ECMA-402? It seems like one or the other is more convenient for different people, so let's take a vote to decide.

Vote :tada: for Slack, :heart: for IRC, and :confused: for skepticism about both/other (please elaborate below)

**Comment by gsathya** [comment]
There seems to be a contingent of ECMA402 folks on the "#tc39-ecma402" channel on Freenode.

**Comment by littledan** [comment]
We concluded that it's fine to try out the IRC channel if you'd like, but the preferred path is to post questions to GitHub, so that they will have the most visibility for collaborators.
