### ISSUE TITLE
Spec formatting issue? Strange line spacing in algorithm steps

### ISSUE THREAD

**Issue by rwaldron** [tc39/ecma402#271]
For example, compare: http://ecma-international.org/ecma-402/#sec-unwrapnumberformat vs https://tc39.github.io/ecma262/#sec-rawbytestonumber

**Comment by littledan** [comment]
That is a spec formatting issue--there should be a "normative optional" box around it, but I don't see that box. Thanks for filing the issue.

**Comment by spectranaut** [comment]
Asked @bterlson about getting back the "normative optional" box in: https://github.com/bterlson/ecmarkup/issues/96

**Comment by spectranaut** [comment]
Oh I didn't realize, but this is fixed in the 2019 version!
