### ISSUE TITLE
Expose dayperiod option in DateTimeFormat

### ISSUE THREAD

**Issue by zbraniecki** [tc39/ecma402#29]
Currently, DateTimeFormat is always displaying dayperiod token if hour12 is set. This is not always matching UX design. 

We have encountered multiple scenarios in which the hour12 setting and dayperiod displaying are controlled separately, including MacOS Date&Time Settings.

I'd like to get dayperiod as another token for DateTimeFormat options as a boolean flag where 'true' means to display it if hour12 is true, and 'false' means not to display it even when hour12 is true.

**Comment by zbraniecki** [comment]
@caridy - would you consider picking it for 3rd edition? It seems like a zero cost change that would help us a lot.

**Comment by caridy** [comment]
I have some issues in Intl.js polyfill around hour12 as well, I will like to know more about this particular use case, then we can discuss the cost of this.

**Comment by zbraniecki** [comment]
Firefox OS UX designs don't use `dayperiod` token of time format even in hour12 clock.
This forces us to do things like:

* https://github.com/mozilla-b2g/gaia/blob/4b1b185afde3bc3bebf3467ef9e257adc46fc58e/apps/system/lockscreen/js/widgets/clock/lockscreen_clock_widget.js#L43-L47
* https://github.com/mozilla-b2g/gaia/blob/d130529c626695570c7b5017d9b43955115d68a0/apps/system/js/time_icon.js#L41-L51

(the latter is also an example for issue #30)

**Comment by zbraniecki** [comment]
I'm finding more example where the developer wants to control if dayperiod is displayed separately from hour12 setting.

The separation between displaying `dayperiod` and time format is also clear in MacOS/iOS: http://imgur.com/FxosgeL

**Comment by zbraniecki** [comment]
Proposal:

```
var formatter = Intl.DateTimeFormat(navigator.languages, {
  hour12: true,
  hour: 'numeric',
  dayperiod: true
  minute: 'numeric'
});
formatter.format(new Date()); // "10:23 PM" in en-US

var formatter = Intl.DateTimeFormat(navigator.languages, {
  hour12: true,
  hour: 'numeric',
  dayperiod: false
  minute: 'numeric'
});
formatter.format(new Date()); // "10:23" in en-US
```

**Comment by caridy** [comment]
Ah, I see what you mean now. Thanks for the example.

Now, it is ambiguous IMO, but that's not my main concern, my issue is that I don't think we have such data in CLDR.

This is the data we have today for `hour12` setup for english:

```json
{
  "h": "h a",
  "hm": "h:mm a",
  "hms": "h:mm:ss a",
  "hmsv": "h:mm:ss a v",
  "hmv": "h:mm a v",
}
```

as you can see, `a` (which is the am/pm token) is in all of them, and removing it manually might produce something that is extraneous for users, for example, the last two also include the timezone details, which means we will end up with something that has timezone details but no dayperiod, seems weird to me. And the algo to select the best match when having `hour12` to true and `dayperiod` to false might be tricky as well.

I wonder what @srl295 and @JCEmmons think about this, and if there is any plan to add such as form into CLDR.

**Comment by zbraniecki** [comment]
> And the algo to select the best match when having hour12 to true and dayperiod to false might be tricky as well.

Yeah, I wrote a mock for our code and it feels a bit shaky. That's why I'd love to get it into the spec, so that people don't have to manipulate the string manually.

@srl295 - any chance CLDR is planning to make it a token that we can add/remove?

**Comment by srl295** [comment]
> Currently, DateTimeFormat is always displaying dayperiod token if hour12 is set. This is not always matching UX design. We have encountered multiple scenarios in which the hour12 setting and dayperiod displaying are controlled separately, including MacOS Date&Time Settings.

How is this used apart from a pattern-based format? In MacOSX, toggling "12/24 hour" adds/removes the dayPeriod. In Custom settings, I can set an explicit format: `h : mm` etc.  

Could you lookup `Hmm` for example which will give you something like `HH:mm` and then map `HH`-->`h` to get `h:mm`?

**Comment by zbraniecki** [comment]
> In MacOSX, toggling "12/24 hour" adds/removes the dayPeriod

That's exactly what we'd like to be able to do.

**Comment by srl295** [comment]
Nevermind, I found it. 
[cldr](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table) 

`J` is the letter of the day.  `J` … 
> … must not occur in pattern or skeleton data. Instead, it is reserved for use in skeletons passed to APIs doing flexible date pattern generation. In such a context, like 'j', it requests the preferred hour format for the locale (h, H, K, or k). However, unlike 'j', it requests no "am/pm" marker (It is typically used where there is enough context that that is not necessary). For example, in en_US with "Jmm", 13:00 would appear as "1:00", while with "jmm", it would appear as "1:00 PM".


`Jm` --> 'hh:mm' for `en_US`, etc

http://apps.icu-project.org/icu4jweb/flexTest.jsp?pat=Jm&_=en_US -> `hh:mm`

**Comment by caridy** [comment]
alright, now it makes even more sense. Here is what we can do:

* add `dayPeriod: <bool>` into the spec, to match what we do today with `hour12`.
* upgrade the algos to take `dayPeriod` and `hour12` into consideration when resolving the pattern.
* update Intl.js

who is up for it? any brave soul? jajaja

**Comment by zbraniecki** [comment]
Do we want to allow for just dayperiod token? I think it would be useful, because then it would be possible to do:

```
var timeString = date.toLocaleString(locale, {
  hour12: true,
  hour: 'numeric',
  minute: 'numeric'
  dayperiod: false
});
var dpString = date.toLocaleString(locale, {
  dayperiod: true
});
element1.textContent = timeString;
element2.textContent = dpString;
```

In that case, I'd say that we should specify it as:
* `dayperiod` can be set to `true` or `false` if it's the only token specified
* or when it's with `hour` and `hour12` is `true` or `undefined`

Does that make sense?

I basically believe that it should be possible to display it alone for the current time, or control if it's displayed when `hour` token is present and `hour12` resolves to `true`.

**Comment by caridy** [comment]
I didn't fully understand what you mean, but these are other considerations:

*  whether that's a value provided by the user, or the default value, there is always a value for `hour12`.
* It seems that day period is only relevant if hour12 is true, otherwise AM/PM will not be present.
* it seems that day period can be provided by the user, or can be true or false based on the value of hour12.
* remember that whatever value we produce in options for hour12 and day period, it is not guarantee to match the resolved options since they are based on the algo to compute the best possible match (which sometimes implies conflicting options)

**Comment by zbraniecki** [comment]
I think we can use #30 to control displaying of `dayperiod` token and we don't need this anymore. Closing.

**Comment by caridy** [comment]
Agreed, let's focus on that for now.
