### ISSUE TITLE
Proposal: support destructor for objects

### ISSUE THREAD

**Issue by dawidgarus** [tc39/ecma402#298]
With the introduction of WASM it's a nice feature to have destructor for garbage collected objects so they can destroy and dispose object created in WASM module.
Imagine following scenario: you want to call JS function with an object that has a reference to an object created on stack (linear memory). The JS function might do some async task after which the object will be collected. At this point you would want to also destroy the object on stack it references to prevent memory leaks.
I propose new well-known symbol - `Symbol.destroy` which should be used to specify function called when object is garbage collected, for example:
```javascript
const obj = {
 [Symbol.destroy]: function() {
  // dispose stuff
 }
};
```
I'm aware that it might complicate GC and has it's own caveats but you see there's very real use case for it.

**Comment by ljharb** [comment]
This seems like you meant to post it on https://github.com/tc39/ecma262, but please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to begin suggesting new features for the language.

**Comment by sffc** [comment]
If you haven't done so already, please file this issue in ECMA 262.

**Comment by littledan** [comment]
Relevant proposal: https://github.com/tc39/proposal-weakrefs/

**Comment by y-nk** [comment]
@dawidgarus did you push for it? I like your proposal, it's simple and reach the goal in few lines.
