### ISSUE TITLE
Proposal: Set API Locale

### ISSUE THREAD

**Issue by leobalter** [tc39/ecma402#337]
As this is a spec we value multi languages, I'd think we would be in the right way if we also offer a localized API structure to support adoption and comprehension for practicioners of the Intl API.

I've been prototyping this for a while and I believe this is a very good path and I believe it should not be contentious at all. The first step would be just setting my favorite locale:

```js
Intl.setMyLocale(['pt-BR', 'ban', 'en']);
```

And then the API provided gets renamed to match my locale set:

```js
Intl.pegarLocalizaçãoCanonica // Intl.getCanonicalLocales
Intl.Agrupador // Intl.Collator
Intl.FormatadorDataHora // DateTimeFormat
Intl.FormatadorListas // ListFormat
Intl.FormatadorNumerico // NumberFormat
Intl.FormatadorPlurais // PluralRules
Intl.FormatadorHoraRelativa // RelativeTimeFormat
...
```

This should also affect the prototype chain:

```js
new Intl.FormatadorDataTempo('en-US').formatar(data));
new Intl.FormatadorDataTempo('en-US').formatarEmPartes(data));
```

It's so intuitive!

The returns should also match the selected locale for the API:

```js
new Intl.FormatadorDataTempo('en-US').formatarEmPartes(data));

// Result:
[
  { tipo: 'day', valor: '17' },
  { tipo: 'weekday', valor: 'Monday' }
]
```

---

This is still Stage 0 but I believe we can already jump to stage 2 or 3 to enable publicly testing on Test262.

The only thing blocking me is resolving RTL languages that I believe they might affect the API ordering and parameters positioning.

Bear in mind this proposal is not only about convenience but it's useful as it helps intuition from the developers around. We can also use it as a success case to make it whole thing for ecma262 including all the Globals.

Please, let me know what you think and hopefully I can have a nice spec candidate done for the next meeting.

**Comment by ljharb** [comment]
Changing the available identifiers by locale seems highly problematic - for linters, polyfills, SES, etc. Separately, making the language stateful also seems concerning.

**Comment by ljharb** [comment]
(－‸ლ) early mornings are early

**Comment by romulocintra** [comment]
lol

**Comment by littledan** [comment]
tbh I think this should be a needs-consensus PR, as it's an obvious bug fix.

**Comment by littledan** [comment]
The only thing is, you shouldn't need to use the English method name to set the locale; you should just use your locale's name for `setMyLocale`, and it should be able to figure it out by the parameter you're passing in.

**Comment by zbraniecki** [comment]
The proposal is brilliant. I'm in particular excited about the opportunity to finally incorporate unicode extension keys to control aspects such as spelling and directionality of the `setMyLocale` name.

One thing we could work on is maybe trying to find a name that, if we're lucky, conflicts with some obsolete, but still in use library in a possibly most catastrophic way. I see it as an opportunity to bring much needed attention, followed by new-found linguistic expertise from members of the community who so far have not been involved in ECMA402.

**Comment by leobalter** [comment]
Sounds great! ~~I'll draft this and maybe force commit the changes directly to master.~~

Thank you all for the appreciation over this proposal. I'm looking forward to all the next enhancements to the Intl specs!

**Comment by sffc** [comment]
I'm not opposed to something like this. There does tend to be a pervasive problem in CS that everything is English-based. That's convenient for me as a native English speaker, but reduces the accessibility of programming in JavaScript to others.

However, I'm not convinced the EcmaScript Spec is the right place for it. Maybe there could be a pre-process step in an external library that maps the symbols correctly.

In terms of implementation, I think a major concern we'd see is that browsers will have to bundle all these new symbols. And then, where do you stop: top 10 languages? Top 50? Top 200? Do you include script and regional variants?

(I see the issue is closed, so I assume it was an April 1 joke.)
