### ISSUE TITLE
Formating fractional minute

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#357]
Mihai Niță (google) during the ECMA402 June meeting mentioned about the issue of format fractional minute. According to my understanding (which could be wrong), here is what he said:
1. ICU currently have no way to format fractional minute
2. If we support fractional second, why not also support format fractional minute?
3. Because we may want to add support to format fractional minute and ICU cannot support format fractional second, and therefore we should not support fractional second. And therefore we should not merge https://github.com/tc39/ecma402/pull/347 until we address this "fractional minute" issue.

Frank's answer: because so far no one propose for such enhancement and you are welcome to propose one and we can discuss that.

Open this ticket and invite Mihai to correct what I wrote above and adding supportive arguments, etc for open discussion.

**Comment by FrankYFTang** [comment]
Just to be clear, we already have 3 different Intl object related "minute"
1. in Intl.DateTimeFormat - eg the "34" in "Sept 21, 2019 12:34:56 PM"
2. in Intl.RelativeTimeFormat - the "12.5" in  "12.5 minutes ago" or "in 12.5 minutes".
3. in Intl.NumberFormat - when use with unit: "minute"

**Comment by FrankYFTang** [comment]
And the Fractional Second  is only about Intl.DateTimeFormat.

**Comment by mihnita** [comment]
Apologies, it was a misunderstanding. Clarified offline.
You can close the issue (I don't seem to have the right to do it myself)
Thank you,
Mihai

**Comment by FrankYFTang** [comment]
based on Mihai's comment, closing it. He said he was thinking about measure format and his case is not for to DateTimeFormat that we were discussing.
