### ISSUE TITLE
Pseudolocales support

### ISSUE THREAD

**Issue by zbraniecki** [tc39/ecma402#36]
Mozilla and Microsoft use a convention of pseudo-locales to help developers ensure their user interfaces are localizable. Two pseudo-locales we use are:

* qps-ploc - slightly wider version of pseudo-english
* qps-plocm - slightly wider version of pseudo-RTL-english

You can see an example screenshot of Firefox OS using qps-ploc here: https://bug900182.bmoattachments.org/attachment.cgi?id=8418596

And Microsoft docs here: https://msdn.microsoft.com/en-us/library/windows/desktop/dd319106%28v=vs.85%29.aspx

It would be helpful if Intl API followed the convention and recognized pseudolocales for Numbers and DateTime formatting.

**Comment by caridy** [comment]
Can you elaborate more on why does this need to be part of the specification? What prevent you from doing so today with some very small library that monkey patch the native implementation to return the mangled form?

**Comment by zbraniecki** [comment]
Nothing. And if this proposal wont get traction, I'll be happy to implement it that way. I just know that Mozilla and Microsoft both use the same pseudo-locales approach to aid developers and thought that there may be enough interest from others to include that into Intl API.

**Comment by caridy** [comment]
I will circle back on this subject next week after TC39.

**Comment by zbraniecki** [comment]
thanks!

**Comment by srl295** [comment]
Relevant: http://unicode.org/cldr/trac/ticket/3971

**Comment by zbraniecki** [comment]
@stas what do you think about Google's approach? Should we try to coordinate with them and Microsoft?

**Comment by srl295** [comment]
@zbraniecki why not register a new bcp47 subtag as proposed in [CLDR 3971](http://unicode.org/cldr/trac/ticket/3971)? Then it won't collide. Otherwise, how can you distinguish `qps` as provided by the 'host' and `qps` as provided by the `Intl` support?

**Comment by zbraniecki** [comment]
It may work. I'm just trying to identify if we can find a common ground between those two (three) implementations.

**Comment by caridy** [comment]
let me talk to @bterlson tomorrow, and see what he thinks about this.

this seems more like a coordination effort rather than a change in the current spec.

**Comment by zbraniecki** [comment]
We aligned our pseudolocales to Google's approach and I think it covers our needs for now - Intl picks up the topmost tag in the language tag and uses appropriate formatting.

In theory, it would be nice to have ability to produce transformed strings according to some pseudolocales rules instead of real strings for locales like `ar` or `fr`, but that's complicated so let's table it for now.

I'm going to close this ticket.

**Comment by zbraniecki** [comment]
btw. Unicode just added `en-XA` and `ar-XB` to CLDR 31 so we should have pseudolocales in Intl API soon :)
