### ISSUE TITLE
Add casing recommendations to style guide

### ISSUE THREAD

**Issue by sffc** [tc39/ecma402#363]
We agreed in https://github.com/tc39/proposal-intl-displaynames/issues/32 to recommend camel case for both keys and enum strings.  We should document this decision in a style guide somewhere so that this discussion doesn't get lost in time.

@leobalter @spectranaut

**Comment by spectranaut** [comment]
this has been added by @sffc : https://github.com/tc39/ecma402/blob/master/docs/style-guide.md
