### ISSUE TITLE
Intl.PluralRules should consider fraction digits and notation

### ISSUE THREAD

**Issue by sffc** [tc39/ecma402#365]
Intl.PluralRules has a very simple API right now.  However, the format of the number, and the notation of the number, affect the plural category.

All of the following have a different plural form in certain languages:

1. `1`
2. `1.0`
3. `1 thousand`

Possible fixes:

1. Allow fraction digits and notation options in Intl.PluralRules (smallest/quickest)
2. Change Intl.NumberFormat to have a `.selectPlural()` method
3. Allow an Intl.NumberFormat object to be passed into Intl.PluralRules
4. Allow the options parameter for Intl.NumberFormat to be passed into Intl.PluralRules

There's a certain elegance to being able to do option 2,

```javascript
const fmt = new Intl.NumberFormat(undefined, {
    minimumFractionDigits: 1,
    maximumFractionDigits: 1
});
console.log(fmt.format(1));  // "1.0"
console.log(fmt.selectPlural(1));  // "other"
```

However, then I'm not sure what we do with Intl.PluralRules.

**Comment by anba** [comment]
Fraction digits is already supported in PluralRules:
```js
js> new Intl.PluralRules("en", {minimumFractionDigits: 0}).select(1.0) 
"one"
js> new Intl.PluralRules("en", {minimumFractionDigits: 1}).select(1.0) 
"other"
```

**Comment by sffc** [comment]
That seems to work in Firefox, hmm, but not Chrome.  I also don't see it on MDN.  I do see it in the spec, though.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules

@FrankYFTang

**Comment by longlho** [comment]
It's in the doc for `resolvedOptions`, but not constructor: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules/resolvedOptions

I'm happy to do a PR

**Comment by FrankYFTang** [comment]
> That seems to work in Firefox, hmm, but not Chrome. I also don't see it on MDN. I do see it in the spec, though.
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules
> 
> @FrankYFTang

This is what I observe on Google Chrome is up to date
Version 77.0.3865.75 (Official Build) beta (64-bit)

new Intl.PluralRules("en", {minimumFractionDigits: 1}).select(1.0) 
> "other"
new Intl.PluralRules("en", {minimumFractionDigits: 0}).select(1.0) 
> "one"
(new Intl.PluralRules("en", {minimumFractionDigits: 1})).resolvedOptions()
> {locale: "en", type: "cardinal", minimumIntegerDigits: 1, minimumFractionDigits: 1, maximumFractionDigits: 3, …}locale: "en"maximumFractionDigits: 3minimumFractionDigits: 1minimumIntegerDigits: 1pluralCategories: (2) ["one", "other"]type: "cardinal"__proto__: Object
(new Intl.PluralRules("en", {minimumFractionDigits: 0})).resolvedOptions()
> {locale: "en", type: "cardinal", minimumIntegerDigits: 1, minimumFractionDigits: 0, maximumFractionDigits: 3, …}locale: "en"maximumFractionDigits: 3minimumFractionDigits: 0minimumIntegerDigits: 1pluralCategories: (2) ["one", "other"]type: "cardinal"__proto__: Object

**Comment by longlho** [comment]
`new Intl.PluralRules("en", {minimumFractionDigits: 1}).select(1) // returns "one"` in Chrome 76

**Comment by sffc** [comment]
> I'm happy to do a PR

Please do :)

@romulocintra @jahzielv

**Comment by FrankYFTang** [comment]
> `new Intl.PluralRules("en", {minimumFractionDigits: 1}).select(1) // returns "one"` in Chrome 76, so fix is in 77?

see https://bugs.chromium.org/p/v8/issues/detail?id=8866
I forgot when and how it got fixed but I am sure it is fixed already on the v8 trunk on v8 trunk Jun 4 and I check in unit test code to ensure the behavior on Jun 6.
Chrome branched m76 on May 30 and branch off m77 on Jul 25.
