### ISSUE TITLE
PluralRules: losing trailing 0 in input

### ISSUE THREAD

**Issue by longlho** [tc39/ecma402#372]
Hi guys,

In `PluralRules.select` spec, input `value` got [`ToNumber`](https://tc39.es/ecma402/#sec-intl.pluralrules.prototype.select) which loses traling zeros. Looks like there needs to be a type check that if `value` is of `string` type, it will be preserved and pass into `GetOperands` as is.

In ICU4J, since `PluralRules` takes in the `FormattedNumber` output from `NumberFormatter`, trailing zeros can be preserved, e.g:

```java
PluralRules.forLocale(locale).select(
	NumberFormatter
		.withLocale(locale)
		.precision(Precision.fixedFraction(3))
		.format(1)
) 
// "other"
```

while in web implementation for `en` locale, `.select('1.000')` returns `one` which isn't accurate.

For reference: https://github.com/formatjs/formatjs/issues/185#issuecomment-530612067

**Comment by sffc** [comment]
I've raised questions about this before; see #365.  I'm closing this as a duplicate.

In hindsight I think an argument could have been made that the plural rule selector should have simply been a method on Intl.NumberFormat.
