### ISSUE TITLE
Intl.PluralRules breaks after 3 decimals

### ISSUE THREAD

**Issue by nbouvrette** [tc39/ecma402#373]
I've noticed the same behavior in both Chrome and Firefox:

```js
new Intl.PluralRules('fr').select('1.999');
```

**Output**:

`"one"`

```js
new Intl.PluralRules('fr').select('1.9999');
```

**Output**:

`"other"`

Both outputs should be `"one"`

**Comment by sffc** [comment]
1.999 stays at 1.999, whereas in Intl.NumberFormat, 1.9999 rounds up to 2 because the default is to round at 3 decimal places.

We should check the spec though to confirm whether Intl.PluralRules is bound by the same rounding rules as Intl.NumberFormat.

**Comment by nbouvrette** [comment]
I could not find any such rounding rules defined anywhere and in that specific case (French) it definitely is breaking plural rules.

I also confirm that ICU4J does not have this behavior.

**Comment by longlho** [comment]
Both PluralRules & NumberFormat default min/maxFractionDigits to 0 & 3 since the use the same SetNumerFormatDigitOption

**Comment by sffc** [comment]
Yep, this is correct.  Intl.PluralRules constructor says, `Perform ? SetNumberFormatDigitOptions(pluralRules, options, 0, 3)` (section [13.1.1](https://ecma-international.org/ecma-402/6.0/index.html#sec-initializepluralrules)).  So, the observed behavior is consistent with the spec.

**Comment by sffc** [comment]
FYI, if you want to disable this rounding behavior, you can set a larger number for maximum fraction digits; for example,

```js
new Intl.PluralRules("fr", { maximumFractionDigits: 12 }).select(1.9999)
// "one"
```

**Comment by nbouvrette** [comment]
My goal is to follow the CLDR specs, but also ideally make sure that those specs reflect practical use cases. I know we are talking about an edge case here but I could not find anywhere on the Unicode site where it is mentioned that the rules should be rounded after 3 digits as a default behavior?

The link you sent seems to be the ECMA spec not the CLDR right? Do you know where those specs are coming from and also why ICU4J has a different behavior? I thought ICU4J was one of the main libraries supported by Unicode.

**Comment by nbouvrette** [comment]
If this help, this is the test I did with ICU4J

```java
ULocale locale = new ULocale("fr");

FormattedNumber number = NumberFormatter.withLocale(locale).format(1.99999);

System.out.println(number);
System.out.println(PluralRules.forLocale(locale).select(number));
```

Output:

```
1.99999
one
```

**Comment by sffc** [comment]
Here are two reasons why it makes sense to set a limit to the number of decimal places:

1. It is consistent with the behavior of Intl.NumberFormat, such that you can use the same options to format a number and get the plural rule for the corresponding formatted number.
2. When you have floating point numbers, setting a fixed number of decimal places sets a clear standard for how to round the floating point number in memory.

The CLDR spec talks about numbers abstractly.  We conform to the spec *after* we convert the floating point number to a "digit list", where we apply the rounding rules.

P.S. ICU4J defaults to 6 decimal places, so if you try 1.9999999, you get the same result as in ECMAScript.

**Comment by nbouvrette** [comment]
Good catch I thought it was up to 15 decimals, but that is actually the maximum `fixedFraction` can handle.

I personally think that 3 decimals is a bit aggressive and think that increasing this to 6 decimals (same as ICU4J) could lower the eventuality of triggering this edge case but if this has a big cost on performance or is not worth the change, I can happily close this issue.

**Comment by sffc** [comment]
> I personally think that 3 decimals is a bit aggressive and think that increasing this to 6 decimals (same as ICU4J) could lower the eventuality of triggering this edge case but if this has a big cost on performance or is not worth the change, I can happily close this issue.

I'm the one who advocated making the new ICU4J NumberFormatter uses 6 instead of 3. :smiley:

You're welcome to open a new issue raising this question for ECMA-402.  It could either apply only to Intl.PluralRules or to both Intl.PluralRules or Intl.NumberFormat.  The problem with changing only Intl.PluralRules is that behavior gets out of sync.  The problem with changing both is that it's an observable behavior change in Intl.NumberFormat that could break the web, and I think it would be hard to make the argument that this case rises to the level to make such a change worthwhile.

**Comment by nbouvrette** [comment]
Thanks for the details - I will go with your advice and close this issue. I can work around the issue for now with `minimumFractionDigits`. 

This can always be an option for those who have the rare case of those using plural with more than 3 digits.
