### ISSUE TITLE
Standard on supported locales

### ISSUE THREAD

**Issue by longlho** [tc39/ecma402#375]
Context: https://bugs.chromium.org/p/chromium/issues/detail?id=1003861&q=pluralrules&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

Looks like we don't have a mandate in the spec in terms of `availableLocales` List, which results in differences in FF vs Chrome:

FF
```js
new Intl.DateTimeFormat('cy').format(Date.now())
// "19/9/2019"
```

Chrome (doesn't load `cy` locale, thus falling back to `en-US`?)
```js
new Intl.DateTimeFormat('cy').format(Date.now())
// "9/19/2019"
```

So my question is: should list of locales be in the spec? Was this discussed before?

**Comment by zbraniecki** [comment]
No. Implementations are free to select which locales they carry and that list may change over time. The mechanism which they use to select a fallback may change as well.
Intl API is "best effort" and users should not assume what is the return value

**Comment by zbraniecki** [comment]
Intl API is intentionally infallible and the output is meant to be opaque.

**Comment by longlho** [comment]
Thanks for the context!
