### ISSUE TITLE
Recommendations for adding CLDR for new locale/unit/currency

### ISSUE THREAD

**Issue by longlho** [tc39/ecma402#379]
Hi there,

Is there a recommended way to add CLDR data for things like unsanctioned units, extra locale or extra currency? The only way I found is to re-include polyfills & load data that way.

Thanks,

LH

**Comment by sffc** [comment]
Are you asking:

(1) How to contribute to real upstream CLDR?
See: http://cldr.unicode.org/index/process

(2) How to build your browser with custom CLDR data?
See: https://github.com/unicode-org/icu/blob/master/docs/userguide/icu_data/buildtool.md

(3) How to add extra data to Intl at runtime?
See: #210

**Comment by longlho** [comment]
Ah I'm looking for #210 then. Thanks!
