### ISSUE TITLE
A way to get a Timezone offset from IANA? 

### ISSUE THREAD

**Issue by danm** [tc39/ecma402#383]
I want to be able to find out a UTC timezone offset by passing a State/territory (Australia/Sydney) into Intl and for it to return the offset.

At the moment, I can do this.

```
const tz = new Intl.DateTimeFormat('en-GB', {
  timeZone: 'Australia/Sydney',
  timeZoneName: 'short',
}).format(new Date());

const diff = tz.split('GMT')[1];
const offset = parseInt(diff, 10);
const offsetMins = offset * 60;
```

Which gets me to where I want to be, but not particularly elegant. I'd love to be able to access the database a little easier, maybe something like.
```
Intl.DateTimeFormat.getOffset('Australia/Sydney');
returns 660
```
Is there a way to do this that I don't know about. (I think this is the first time I have used the Itnl class)

**Comment by aphillips** [comment]
Note well: the offset can change depending on the date/time in zones that use DST. In addition, offsets have changed historically (and will do again in the future)... so your offset getter needs an Instant. (raw offset for the current date is only marginally useful)

**Comment by littledan** [comment]
This is proposed as part of the `Temporal.TimeZone` API in the [Temporal proposal](https://github.com/tc39/proposal-temporal).

**Comment by danm** [comment]
From the docs

A Temporal.TimeZone represents an IANA Timezone, a specific UTC-Offset or UTC itself. Because of this Temporal.TimeZone can be used to convert between `Temporal.Absolute` and `Temporal.DateTime` as well as finding out the offset at a specific `Temporal.Absolute`.

`Temporal.TimeZone` is also an iterable that give access to the [IANA-Timezones supported by the system](https://www.iana.org/time-zones) from the IANA time zone database ([also listed here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)).

See `Temporal.TimeZone` Documentation for more detailed documentation.

😍 😍 😍 😍
