### ISSUE TITLE
Propose for way to display alternative symbol currency variant for Number.prototype.toLocaleString() and Intl.NumberFormat

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/ecma402#4]
Notice the issue in https://github.com/andyearnshaw/Intl.js/pull/84
Actually I have three proposals:
1) Change "symbol" and "symbol-alt-variant" for "RUB" currency in CLDR. The ₽ symbol is official since 2014 and many people already use it and you can even see it on coins in Russia now.
2) Add a way to display alternative symbol currency variant for `Number.prototype.toLocaleString()` and `Intl.NumberFormat`. There is already `currencyDisplay` option but it can be only `name`, `symbol` or `code` and there is no way to display alternative symbol.
3) Add a way to display custom symbol currency variant. This will be useful in situations when some official currency symbol was changed but specification is in progress of adopting these changes. So one can override currency symbol. Also this may be useful for some virtual currencies some websites may use for their specific purposes.

**Comment by caridy** [comment]
1) you should probably open an ticket on CLDR: http://unicode.org/cldr/trac/newticket, to try to get more information about `symbol-alt-variant`, and where and when `₽` will become the defacto symbol if that's the intent.

2) This is probably more realistic, although only few locales in CLDR have more than name, symbol and code, a fallback mechanism has to be defined if the `alt` symbol is enabled.

3) This is more problematic, in general ECMA-402 does not allow users to specific anything outside of the domain of data we know about, and I don't see that changing anytime soon.

**Comment by chicoxyzzy** [comment]
I can try to make a proposal for symbol-variant option but I don't know CLDR sources and spec good enough. I've found (`₽` symbol)[http://www.unicode.org/cldr/charts/27/summary/ru.html#4582] in CLDR but I still don't know what in spec should be changed to add symbol-variant option. Should it be `currencyDisplay`? Can you point me into right direction?

**Comment by rxaviers** [comment]
Perhaps a [variant subtag][] could be specified in the locale. @srl295 is there any for that purpose? I don't see any mention at http://www.unicode.org/reports/tr35/tr35-numbers.html#Currencies.

[variant subtag]: http://www.unicode.org/reports/tr35/#unicode_variant_subtag

**Comment by JCEmmons** [comment]
There isn't any variant specified in tr35 that would support this.


Regards,

John C. Emmons
Globalization Architect & Unicode CLDR TC Chairman
IBM Software Group
Internet: emmo@us.ibm.com

**Comment by rxaviers** [comment]
Thanks John. Does ICU allow using these values? If so, how please?

**Comment by JCEmmons** [comment]
As far as I know, they don't currently support it in the "stock ICU".  I 
think you can build ICU using the alternate currency symbol, but then that 
symbol would be the only one available.


Regards,

John C. Emmons
Globalization Architect & Unicode CLDR TC Chairman
IBM Software Group
Internet: emmo@us.ibm.com

**Comment by bterlson** [comment]
Possibly useful to note that Chakra seems to be using the new currency symbol:

    Intl.NumberFormat("ru-RU", { style: 'currency', currency:"rub", currencyDisplay: "symbol"}).format(123213); => "123 213,00 ₽"

Seems like the path of least resistance here is just to update the symbol in CLDR and call it a day?

**Comment by caridy** [comment]
:+1: on @bterlson's suggestion to align with Chakra, considering that it is way ahead in terms of locale data support for currency as far as I can tell.

@JCEmmons how feasible is that?

**Comment by JCEmmons** [comment]
Anything is doable.  FYI - I have already updated the default symbol for RUB to "₽" in CLDR 28 for those locales where the Cyrillic abbreviation stood previously ( be, bg, kk, os-RU, ru, sah, and wae ), ( see http://unicode.org/cldr/trac/ticket/8287 ), but that's not shipping until September. We could do a maintenance release, but to be honest right now I'm not inclined to do it unless you can convince me that it's really time critical.

A new -u locale extension could be created, (i.e. something like "ru-RU-u-cs-variant", where "cs" means "currency symbol", but in my opinion the benefit gained probably outweighs the amount of work here.  If you want to go this route, then filing a ticket in CLDR land is probably the first step, and the committee can look at it.

**Comment by caridy** [comment]
September sounds wonderful to me! :)

**Comment by caridy** [comment]
@JCEmmons any update on this?

**Comment by chicoxyzzy** [comment]
I hope this issue will be mention on upcoming TC39 meeting in September.
Some related thoughts in [agendas repo commit comment](https://github.com/tc39/agendas/commit/8985b13feba3963c58c063c05ac2a430b490e3b6#commitcomment-23399555)

**Comment by chicoxyzzy** [comment]
Reposting my comment here.

--------------
I'm excited about ICU discussion at TC39 meeting!
There is an old issue about updating something related to ICU [on GitHub](https://github.com/tc39/ecma402/issues/4) and [CLDR tracker](http://unicode.org/cldr/trac/ticket/8287). I know couple companies (including FinTech company I work for, 2 or 3 banks and flight tickets aggregator) which decided not to use `Intl.NumberFormat` for currencies just because some currency symbols simply doesn't work in most of locales. For example `₽` (Russian Ruble) symbol is official since 2014 and it looks strange when someone arguing (as in CLDR issue) that not adding it as default root symbol is caused by its lack of
> widespread enough understandability

while
- there are no any metrics on widespread enough understandability
- there is an egg vs chicken problem of spreading new (for some people) symbols

I understand that new symbols might be confusing for a lot of people and that's why we need https://github.com/zbraniecki/proposal-intl-formatToParts ASAP.

I didn't found the right place to open an issue and I'll be happy create it in proper repo!

I really hope on improving ICU standartization! Thank you for working on this!

**Comment by chicoxyzzy** [comment]
`Intl.formatToParts` will make it possible to add default HTML `title` attribute for alternate text symbol representation.

**Comment by littledan** [comment]
This really seems like an issue for CLDR, not this specification. This specification leaves the data contents up to the implementation to support. Exposing those contents is much of the whole point.

I think if we wanted Intl.NumberFormat to really work well in Fintech, we'd need more features than this, for example more advanced fractional output modes. Intl.NumberFormat is probably best for more basic, "consumer" use cases.

**Comment by caridy** [comment]
let's close this one since it does not require any change in 402.
