### ISSUE TITLE
Canonicalise Unicode extensions options added through ResolveLocale

### ISSUE THREAD

**Issue by leobalter** [tc39/ecma402#413]
The PR #175 landed after `Intl.Locale`, but didn't fix the issue outlined in <https://github.com/tc39/proposal-intl-locale/issues/96>. Maybe revert the PR for now?

_Originally posted by @anba in https://github.com/tc39/ecma402/pull/175#issuecomment-591879408_

**Comment by leobalter** [comment]
@anba as we are currently at the Intl meeting I'm taking the opportunity to see if we can make a decision here so we could avoid reverting the PR.

If it requires extra time, I'll need to postpone #175 for after the ES2020 cut anyway.

**Comment by leobalter** [comment]
and thanks for reminding me of this issue.

**Comment by sffc** [comment]
IIRC, @jswalden was going to help write up some spec for this.
