### ISSUE TITLE
Table 1, 2, 3 "not found" using latest ecmarkup

### ISSUE THREAD

**Issue by rwaldron** [tc39/ecma402#42]
Errors look like: 

```
[2015-09-29T14:37:25.218Z] Warning: can't find clause, production, note or example with id #table-1
...
```

Using eg. `<emu-clause id="table-1">`: 

```
Error: Clause doesn't have header: <emu-clause id="table-1">
```

But we don't want a header here and tables aren't:

- a clause
- a note
- a production

----

Using eg. 

```html
<emu-example id="table-1">
  <figure>
    <figcaption>Table 1 &mdash; Collator options settable through both extension keys and options properties</figcaption>
    <table class="real-table">
...
    </table>
  </figure>
</emu-example>
```

Looks more like what we want, but includes a generated `<figcaption>` that we don't want: 

![](https://i.gyazo.com/ff7a4c5ac0cb9ddf6835386680864f64.png)

Maybe @bterlson has advice? Maybe we need an `<emu-figure>`?

```html
<emu-figure id="table-1">
  <figcaption>...</figcaption>
  <table>...</table>
</emu-figure>
```

Note that `<figure id=...>` has same error.

**Comment by rwaldron** [comment]
Looks like there IS an `<emu-table>`!

**Comment by caridy** [comment]
yeah, that was introduced because of this spec :)
