### ISSUE TITLE
Explicitly state in the spec why we don't have parse methods

### ISSUE THREAD

**Issue by sffc** [tc39/ecma402#424]
We have received requests for parsing on numerous occasions; for example, #1, #147, and #342.  Besides the discussion in those threads, I've also written a [blog post](https://blog.sffc.xyz/post/190943794505/why-you-should-not-parse-localized-strings) on the subject.

Because such bugs won't stop coming in, and because the personnel on this committee may change and forget why we consistently have shot the idea down, I think it would be beneficial to add a paragraph to the specification document itself laying out why exactly we feel that parsing methods don't belong in ECMA-402.

**Comment by littledan** [comment]
I've gotten this question lots of times too. Good to know about your blog post, so I can refer people to it in the future!

**Comment by ryzokuken** [comment]
@sffc where do you think this note should go?

**Comment by sffc** [comment]
Add a paragraph in Section 4 "Overview", either underneath one of the existing headings, or under a new heading if it doesn't fit on any of the existing headings.

https://tc39.es/ecma402/#overview
