### ISSUE TITLE
Should [[RelevantExtensionKeys]] be pre-alphabetized?

### ISSUE THREAD

**Issue by rkirsling** [tc39/ecma402#427]
If UTS 35 expects a canonical locale identifier to have its extensions alphabetized, should we update the [[RelevantExtensionKeys]] lists for [Collator](https://tc39.es/ecma402/#sec-intl-collator-internal-slots) and [DateTimeFormat](https://tc39.es/ecma402/#sec-intl.datetimeformat-internal-slots) to have `kf` before `kn` and `hc` before `nu`, respectively?

There's no alphabetization to do if the list is already in order, and I don't believe this has any impact on the initialization of either class, since we access the options by name.

**Comment by littledan** [comment]
@rkirsling It sounds like this would be an editorial change, right? If so, I'm in favor of it.
