### ISSUE TITLE
Editorial: No MinuteFromTime and SecondFromTime in ECMA262

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#428]
Found an editorial issue 

https://tc39.es/ecma402/#table-datetimeformat-tolocaltime-record
Table 7 show

Field | Value Calculation for Gregorian Calendar
-- | --
...
[[Minute]] | MinuteFromTime(tz) specified in ES2021's Hours, Minutes, Second, and Milliseconds
[[Second]] | SecondFromTime(tz) specified in ES2021's Hours, Minutes, Second, and Milliseconds

But there are no MinuteFromTime nor SecondFromTime
in https://tc39.es/ecma262/#sec-hours-minutes-second-and-milliseconds
There are only MinFromTime and SecFromTime

MinuteFromTime should be renamed as MinFromTime
SecondFromTime should be renamed as SecFromTime

**Comment by anba** [comment]
Was fixed in #486.
