### ISSUE TITLE
Displaying wrong number format for en-IN locale

### ISSUE THREAD

**Issue by kalpeshsingh** [tc39/ecma402#432]
India has its own official number system popularly known as Indian System of Numeration. The system has two major distinctions - Separators (denoted by comma) and the notation (lakh, crore etc.).

| en-US | IN (Oral) | IN (Written) |
|------------|---------------|------------------|
| 100,000 | 1 lakh (abbreviated L) | 1,00,000 |
| 1 million | 10 lakh | 10,00,000 |
| 10 million | 1 crore (abbreviated cr) | 1,00,00,000 |

The following code produces wrong format for Indian numbers in `en-IN` locale where as `hi-IN` produces expected result.

```
const formatConfig = {
  notation: 'compact',
  compactDisplay: 'short'
};
const number = 100000;

const formatIndiaHindi = new Intl.NumberFormat('hi-IN', formatConfig).format(number);
console.log(formatIndiaHindi); //  "1 लाख"

const formatIndiaEnglish = new Intl.NumberFormat('en-IN', formatConfig).format(number);
console.log(formatIndiaEnglish); //  "100K"

// 👆 This should have produced "1L" instead of "100K"

```

System Information
| Browser | OS |
|-------------------------------------------------|--------------|
| Chrome - Version 81.0.4044.129 (Official Build) (64-bit) | macOS Mojave (10.14.6) |

Access the code online on [JSBin](https://jsbin.com/pehawocavo/1/edit?js,console).

### Resources
- [Indian Numbering System](https://en.wikipedia.org/wiki/Indian_numbering_system) - Wikipedia
- [Knowing Your Number](https://nroer.gov.in/nroer_team/file/readDoc/55b23f2881fccb054b6be25f/). Refer Page 10.
Department Of School Education And Literacy, National Repository of Open Educational Resources

**Comment by ryzokuken** [comment]
@sffc is this a CLDR issue? I don't think CLDR has any special data for `en_IN`.

**Comment by littledan** [comment]
CLDR has plenty of special data for en-IN, but its support for lakh and crore abbreviations seems inexplicably partial--it only includes them for currency, and omits them for ordinary numbers. Here's an example:

```
const formatConfig = {
  notation: 'compact',  // I guess this causes fallback to non-compact data in all cases
  style: 'currency',
  currency: 'INR'
};
const number = 100000;

const formatIndiaHindi = new Intl.NumberFormat('hi-IN', formatConfig).format(number);
console.log(formatIndiaHindi); //  ₹1 लाख

const formatIndiaEnglish = new Intl.NumberFormat('en-IN', formatConfig).format(number);
console.log(formatIndiaEnglish); //  ₹1L
```

If you look in CLDR, in [`main/hi.xml`](https://github.com/unicode-org/cldr/blob/release-37/common/main/hi.xml#L5295), you'll see several patterns for lakh, crore and higher abbreviations in both `<currencyFormat>` and `<decimalFormat>` tags. However, in [`main/en_IN.xml`](https://github.com/unicode-org/cldr/blob/release-37/common/main/en_IN.xml#L5254), only `<currencyFormat>` abbreviations are present, and not `<decimalFormat>`.

I'm not sure if there's any linguistic reason for this absence, or if it's just an omission (sounds like the latter?). The next step here would be to [file a ticket in CLDR's JIRA](https://unicode-org.atlassian.net/projects/CLDR).

**Comment by sffc** [comment]
@littledan's comment is correct.  This sounds like a CLDR bug.  Please follow the link to file a ticket on CLDR JIRA, and reference this bug when you file it.

https://unicode-org.atlassian.net/projects/CLDR

**Comment by littledan** [comment]
(It's a tangent, but I'm curious: if you are not in compact mode, would you prefer to see "1L" or "1 lakh"?)

**Comment by kalpeshsingh** [comment]
> (It's a tangent, but I'm curious: if you are not in compact mode, would you prefer to see "1L" or "1 lakh"?)

If I get choice to choose between `lakh` and `L` then I would prefer `lakh`. Short form can be confusing specially in the country where people are not used to with short notation. That's my personal view. 

Fun fact - Indian bank passbook uses `cr` to denote `credit` in the passbook entries.

**Comment by kalpeshsingh** [comment]
> @littledan's comment is correct. This sounds like a CLDR bug. Please follow the link to file a ticket on CLDR JIRA, and reference this bug when you file it.
> 
> https://unicode-org.atlassian.net/projects/CLDR

Thank you @ryzokuken for initiating discussion.

I have filed the [issue](https://unicode-org.atlassian.net/browse/CLDR-13759) in CLDR's Jira and referenced this issue there.
Thank you @sffc for giving direction and @littledan for diving deep and investigating.

**Comment by kalpeshsingh** [comment]
@littledan - I was playing with currency example you posted above and found few things. 

If I pass `currency: 'USD'` then output for `hi-IN` and `en-IN` is different. 

| hi-IN | en-IN |
|-------------------------------------------------|--------------|
| `$1 लाख` | `US$1L` |

Where as other currencies has below result which is consistent with both Indian locales.

#### Australian Dollar (AUD)
 
| hi-IN | en-IN |
|---|---|
| `A$1 लाख` | `A$1L` |


#### Canadian Dollar (CAD)

| hi-IN | en-IN |
|---|---|
| `CA$1 लाख` | `CA$1L` |


#### Hong Kong Dollar (HKD)

| hi-IN | en-IN |
|---|---|
| `HK$1 लाख` | `HK$1L` |

#### Euro

| hi-IN | en-IN |
|---|---|
| `€1 लाख` | `€1L` |


Do you think that USD too should have `US` prefix before `$` sign in `hi-IN`?

**Comment by littledan** [comment]
> Fun fact - Indian bank passbook uses cr to denote credit in the passbook entries.

Wow, that sounds a bit confusing. FWIW CLDR uses capitalized "Cr" for these contexts. I'm kinda curious if that functions to disambiguate.

> Do you think that USD too should have US prefix before $ sign in hi-IN?

Sorry, I don't have any knowledge of Hindi or Indian English, but maybe @ryzokuken would have some thoughts of what the output should be, given his linguistic background.

What would you think of following up here in the CLDR issue, and closing the issue in this repo? I don't see any action to take on the ECMA-402 side, but I'm glad you raised this issue so we could follow up and fix it.

**Comment by kalpeshsingh** [comment]
Tracking issue in [CLDR Jira](https://unicode-org.atlassian.net/browse/CLDR-13759) and closing this one.

Though, Feel free to post new updates or reply to previous comments.

**Comment by ryzokuken** [comment]
> Sorry, I don't have any knowledge of Hindi or Indian English, but maybe @ryzokuken would have some thoughts of what the output should be, given his linguistic background.

Thanks @littledan. I think removing the `US` prefix in `en-IN` should suffice consistency-wise. @kalpeshsingh would you like to file a separate issue for that in CLDR?

Also, thanks again for filing this issue here, we were able to take appropriate action.

**Comment by kalpeshsingh** [comment]
> @kalpeshsingh would you like to file a separate issue for that in CLDR?

I will do that.
Thanks!
