### ISSUE TITLE
ES2021 Intl.NumberFormat ComputeExponent Step 8 bug?

### ISSUE THREAD

**Issue by pyrocat101** [tc39/ecma402#440]
In [ComputeExponent][] step 8.

> Let newMagnitude be the base 10 logarithm of x rounded down to the nearest integer.

I think this is a bug. Instead of computing the magnitude of `x`, it should compute the magnitude of `formatNumberResult.[[RoundedNumber]]` from step6.

We found this when implementing the polyfill. Related issue: https://github.com/formatjs/formatjs/issues/1670

  [ComputeExponent]: https://tc39.es/ecma402/#sec-computeexponent

**Comment by sffc** [comment]
Yes, this is definitely a bug.  It's sloppy.  I would consider it an editorial fix.  Do you want to open a PR to fix it?
