### ISSUE TITLE
Synchronize abstractions from 262

### ISSUE THREAD

**Issue by leobalter** [tc39/ecma402#441]
@FrankYFTang has reported the `OrdinaryObjectCreate` replacing an old `ObjectCreate` abstraction. We need to keep this and perhaps other names in sync here.

**Comment by ljharb** [comment]
the old one is `ObjectCreate`. The other two removed between 2019 and 2020 aren't in use in 402.

**Comment by leobalter** [comment]
It was a typo, thanks for flagging that and for the quick recap on what have changed.
