### ISSUE TITLE
Double canonicalization issue: Intl.Locale.toString output is not a valid Intl.Locale input

### ISSUE THREAD

**Issue by longlho** [tc39/ecma402#445]
When `und` is involved this seems to break compared to other use cases:
```ts
new Intl.Locale(new Intl.Locale('und-x-private').toString())
```
triggers
```
Uncaught RangeError: Incorrect locale information provided
    at new Locale (<anonymous>)
    at <anonymous>:1:1
```
since `und-x-private` got canonicalized into `x-private`, thus no longer a valid `unicode_locale_id` production.

This specifically affects https://tc39.es/ecma402/#sec-apply-options-to-tag Step 9 & 10 where `tag` is canonicalized, then `language` from options got applied, then canonicalized again which can break

**Comment by longlho** [comment]
A more obvious breakage is
```
new Intl.Locale('und-x-private').minimize()
```
triggers
```
VM590:1 Uncaught RangeError: Incorrect locale information provided
    at Locale.minimize (<anonymous>)
    at <anonymous>:1:34
```

**Comment by anba** [comment]
This sounds like a V8 bug (cc @FrankYFTang), `und-x-private` shouldn't have been canonicalised to `x-private` in the first place.

**Comment by sffc** [comment]
@FrankYFTang Can you take a look at this?

**Comment by FrankYFTang** [comment]
yea, that is a v8 bug https://bugs.chromium.org/p/v8/issues/detail?id=10682

**Comment by sffc** [comment]
Thanks for looking, Frank!  I will close this issue since it is now being tracked downstream.
