### ISSUE TITLE
Default values for relevant extension keys in spec

### ISSUE THREAD

**Issue by longlho** [tc39/ecma402#455]
As I'm working on the `Intl.DateTimeFormat` polyfill for ES2021 which has a bunch of extension keys but everything has `undefined` as the default value. Locale, however, has specific wording in [`DefaultLocale`](https://tc39.es/ecma402/#sec-defaultlocale) that delegate that to the host environment. 
Some examples of issues I saw during implementation are:
- ECMA-402 & 262 clearly favors `gregorian` calendar, but it's not the default, so in https://tc39.es/ecma402/#sec-tolocaltime it falls through to the impl-dependent behavior which is vague
- Same thing with `numberingSystem`
- Wording in https://tc39.es/ecma402/#sec-properties-of-intl-datetimeformat-instances indicates that those values must be a UTS35-conforming String type

So my question is, is it up to the implementation to choose such default values?

**Comment by sffc** [comment]
I think the section you want is this one:

https://tc39.es/ecma402/#sec-Intl.RelativeTimeFormat-internal-slots

It shows that each locale can have its own default [[nu]], [[hc]], and [[ca]].  You can get those default preferences (mapping from locale to [[nu]], [[hc]], or [[ca]]) from CLDR data.

I did notice something strange in that section, which is that [[nu]] and [[hc]] are clearly listed in [[LocaleData]], but [[ca]] is not. @leobalter @gibson042 ?

**Comment by anba** [comment]
> I did notice something strange in that section, which is that [[nu]] and [[hc]] are clearly listed in [[LocaleData]], but [[ca]] is not.

This is covered through [9.1 Internal slots of Service Constructors](https://tc39.es/ecma402/#sec-internal-slots):
> [[SortLocaleData]] and [[SearchLocaleData]] (for Intl.Collator) and [[LocaleData]] (for Intl.NumberFormat, Intl.DateTimeFormat, Intl.PluralRules, and Intl.RelativeTimeFormat) are records that have fields for each locale contained in [[AvailableLocales]]. The value of each of these fields must be a record that has fields for each key contained in [[RelevantExtensionKeys]]. The value of each of these fields must be a non-empty list of those values defined in Unicode Technical Standard 35 for the given key that are supported by the implementation for the given locale, with the first element providing the default value.

**Comment by longlho** [comment]
Gotcha thanks for the clarification!
