### ISSUE TITLE
Editorial: If x is not undefined, then A  / Else B

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#458]
There are several places in the ECMA402 spec that we have the following pattern

```
1. If X is not undefined, then
  a. AAAA
2. Else,
 b. BBBB
```

I think that double negative is just harder to read. Could we change them to
```
1. If X is undefined, then
  a. BBBB
2. Else,
 b. AAAA
```

**Comment by ben-allen** [comment]
Is this one already resolved? There currently isn't anything in the spec with the pattern:

1. If X is not undefined, then
  a. AAAA
2. Else,
 b. BBBB

The only occurrences of 
1. If X is not undefined, then
  a. AAAA

have no associated else clause.

**Comment by FrankYFTang** [comment]
I. https://tc39.es/ecma402/#sec-initializedatetimeformat step 42 and 43
42. If dateStyle is not undefined or timeStyle is not undefined, then
Block A
43. Else
Block B

could we change it to (notice the removal of "not" and "or"=>"and"
42. If dateStyle is undefined and timeStyle is undefined, then
Block B
44. Else
Block A

II. https://tc39.es/ecma402/#sec-setnfdigitoptions
Step 17 and 18
```
17. If mnsd is not undefined or mxsd is not undefined, then
a. Let hasSd be true.
18. Else,
a. Let hasSd be false.
```
How about
```
17. If mnsd is undefined and mxsd is undefined, then
a. Let hasSd be false.
18. Else,
a. Let hasSd be true.
```

and step 19 & 20
```
19. If mnfd is not undefined or mxfd is not undefined, then
a. Let hasFd be true.
20. Else,
a. Let hasFd be false.
```
How about
```
19. If mnfd is undefined and mxfd is undefined, then
a. Let hasFd be false.
20. Else,
a. Let hasFd be true.
```

**Comment by ben-allen** [comment]
Not sure how I missed those -- thank you for the heads-up!
