### ISSUE TITLE
Add RelativeTimeFormat and Locale to "API Overview" section

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#468]
https://tc39.es/ecma402/#sec-api-overview doesn't yet mention `Intl.RelativeTimeFormat` and `Intl.Locale`.

**Comment by leobalter** [comment]
My bad on this. 

I'll try to do within a week span, unless @gibson042 or someone else is interested.

**Comment by sffc** [comment]
I mentioned this in https://github.com/tc39/ecma402/pull/456#issuecomment-647860767.  We could do this as a separate PR, or just make sure Intl.ListFormat updates Section 4 and also add the other two classes at the same time.

**Comment by romulocintra** [comment]
This was partially addressed by https://github.com/tc39/ecma402/commit/6163a1809e4d39d796c8b25a7b8a23a0265009fa#diff-dabc9cd8ee17bfa67f04322dcb7f6e0eeaa3a7b33f12b14b47b2925bdfcbc882L32 where constructor names are no longer enumerated.  Additionally, this [PR](https://github.com/tc39/ecma402/pull/613/files) may address this.

**Comment by gibson042** [comment]
Agreed; this is now fixed.
