### ISSUE TITLE
ResolveLocale with `nu` for NumberFormat

### ISSUE THREAD

**Issue by longlho** [tc39/ecma402#479]
This is more of a question than an issue:
When initializing `NumberFormat` with a `numberingSystem` (say, `adlm`). In https://tc39.es/ecma402/#sec-initializenumberformat step 9 - 11, `ResolveLocale` is called with `opt.nu = 'adlm'`. In https://tc39.es/ecma402/#sec-resolvelocale step 9.i.iv it says

> If keyLocaleData contains optionsValue, then [...]

Does that mean for the extension `nu`, the locale data is supposed to contains ALL numbering systems?  How does that work w/ grouping symbols and such? (Since CLDR seems to only have a subset of those for some numbering systems)

**Comment by sffc** [comment]
The grouping symbol is ILND.

I think the idea is that `keyLocaleData` contains keys for all numbering systems for which you have data or interesting behavior.  The list of numbering systems needs to be a superset of Table 4.
