### ISSUE TITLE
Tracking the new algorithm convention for return-if-abrupt

### ISSUE THREAD

**Issue by rwaldron** [tc39/ecma402#48]
https://github.com/tc39/ecma262/pull/129

**Comment by bterlson** [comment]
I have a node script to do the conversion if you're interested.

**Comment by rwaldron** [comment]
Yep, I think @caridy and I would prefer mechanically updating vs manual

**Comment by caridy** [comment]
:) will ping on thru to get it.

**Comment by bterlson** [comment]
It's still being edited now, so I'll give you the final version once tc39/ecma262#129 is accepted.

**Comment by caridy** [comment]
fixed in various commits, we no longer use return-if-abrupt form in 402, we use either `?` or `!`
