### ISSUE TITLE
https://ecma-international.org/ecma-402/7.0/index.html JS issue

### ISSUE THREAD

**Issue by longlho** [tc39/ecma402#484]
Seems to be missing some assets?

![image](https://user-images.githubusercontent.com/198255/87867480-0f0df000-c95b-11ea-8b13-e7d7dd0c1381.png)

None of the permalink hover over title seems to work :(

6.0 seems to work fine

**Comment by ljharb** [comment]
Thanks; I've notified the responsible parties.

**Comment by leobalter** [comment]
It seems like the problem has been fixed.x
