### ISSUE TITLE
Windows timezones

### ISSUE THREAD

**Issue by dilyanpalauzov** [tc39/ecma402#492]
Apart from the IANA Olson timezone names, there are Windows timezone names like FLE Standard Time.  Some people read the current specification in such a way, that an Intl implementation has to reject a Windows-only timezone name:

https://github.com/nodejs/node/issues/34511

Please clarify in the specification, that implementations are allowed to interpret Windows-only timezones (on Linux).

**Comment by zbraniecki** [comment]
> Please clarify in the specification, that implementations are allowed to interpret Windows-only timezones (on Linux).

Only IANA is supported by ECMA402.
