### ISSUE TITLE
PR merge workflow

### ISSUE THREAD

**Issue by sffc** [tc39/ecma402#496]
Should Editors be the only ones with the merge button to the repo, or should all TG2 members get the button as long as there is an editor's approval?

@leobalter @gibson042

**Comment by leobalter** [comment]
For my considerations as an editor: I'm fine either way. Although, I believe the merge button might become useful to help with the flow and might give everyone at TG2 a better sense of ownership of this repo.

The responsibilities of the editors remain, but this is a collective work I want everyone to feel highly involved and proud of the results.

There is no big risk in adding this button. Said that, we may set protections to avoid direct commits to master for everyone, including editors.

## The counter argument

During the TG2 meeting today, there was also a sentiment that making the merge button exclusive to editors will give a better sense of responsibility and process. This argument is not only valid as I like it the same way.

## Status Quo

As I'm positive with both ends, I believe we can just maintain current status quo (merge button exclusive to editors) unless any new point stands out.

**Comment by ben-allen** [comment]
We're sticking with the status quo (merge button exclusive to editors)
