### ISSUE TITLE
JavaScript error prevents the standard from rendering correctly.

### ISSUE THREAD

**Issue by mhorowitz** [tc39/ecma402#505]
https://ecma-international.org/ecma-402/ does not work correctly in Firefox on my Mac.  The search box does not work, and the arrows don't reveal any sections.  There are other issues as well.

In the JS console, I see
```
Loading failed for the <script> with source “https://ecma-international.org/ecma-402/ecma-402/ecmarkup.js”.
```
In the source
```
<script src="ecma-402/ecmarkup.js"></script>
```
looks incorrect. I believe it should be just
```
<script src="ecmarkup.js"></script>
```

I poked around a few of the GitHub branches, but I didn't find one in which `spec/index.html` looked incorrect.

**Comment by ljharb** [comment]
Thanks; I've notified ecma and asked them to fix it.
