### ISSUE TITLE
Include Set Timezone WebDriver extension to allow testing of different timezone? 

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#507]
While I try to [improve the testing infrastructure to allow the web platform test](https://github.com/web-platform-tests/rfcs/issues/66) to set timezone of the use agent to verify the timezone ID returned by ECMA402 API, I got requested to place [the proposed "Set Timezone WebDriver extension specification"](https://docs.google.com/document/d/12vdPTH_Vlkt4pxwlWzR1CjKtLE6y2Z-Qs-GPi_hWXqc/edit#) into a 'standard". The possible candidates of such "standard" are  1) HTML standard 2) webdrive specification 3) ECMA402.

Since HTML standard does not have a concept of "default timezone id" I do not think 1) is the right place
2) is possible but I am not sure how fast/slow the process is I filed https://github.com/w3c/webdriver/issues/1559 to test the water.
I would like to see would 3) ECMA 402 itself is the right place since the API expose such ID currently is only from ECMA function calls ( (new Intl.DateTimeFormat().resoledOptions().timeZone )

**Comment by aphillips** [comment]
Right now HTML doesn't have any concept of time zone--only of offsets. This is a gap in HTML, since it makes it difficult to support things affected by time zones (such as Daylight/Summer Time transitions in forms). The W3C I18N WG has long championed the addition of IANA ids to HTML, but gained little traction. As browsers will end up supporting time zones in ECMA-402, wouldn't it make sense to get HTML to define time zones (including a default time zone that could then be driven) in HTML also?

**Comment by FrankYFTang** [comment]
> Right now HTML doesn't have any concept of time zone--only of offsets. This is a gap in HTML, since it makes it difficult to support things affected by time zones (such as Daylight/Summer Time transitions in forms). The W3C I18N WG has long championed the addition of IANA ids to HTML, but gained little traction. As browsers will end up supporting time zones in ECMA-402, wouldn't it make sense to get HTML to define time zones (including a default time zone that could then be driven) in HTML also?

I am not sure the answer for that question. how would you define that in term of HTML?

**Comment by mathiasbynens** [comment]
@aphillips Note that https://github.com/whatwg/html/pull/3047 introduces the concept to HTML by cross-referencing other specs.

For the WebDriver extension, it increasingly seems like adding a new section to the HTML Standard as part of https://github.com/whatwg/html/pull/3047 might be the best solution. cc @littledan

**Comment by leobalter** [comment]
As we discussed in our monthly meeting, my PoV on this is for this feature not being a fit for ECMA-402 like others shared this sentiment.

At the same time, it's very hard to speculate about other standards this should go, this involves a lot of assumptions we can't take for granted.

I believe @sffc might share the final conclusion from the meeting.

**Comment by sffc** [comment]
Meeting minutes: https://github.com/tc39/ecma402/blob/master/meetings/notes-2020-11-05.md#include-set-timezone-webdriver-extension-to-allow-testing-of-different-timezone-507

Official consensus of TC39-TG2: *We do not want 402 to be the source of the web platform's default time zone, and we don't want to expose a hook for it.*  See the minutes for more details.

**Comment by sffc** [comment]
I'm closing this in accordance with the consensus documented above.

**Comment by sffc** [comment]
CC @mj1856
