### ISSUE TITLE
Wiki no longer editable

### ISSUE THREAD

**Issue by longlho** [tc39/ecma402#509]
I'm trying to add the link for `DateTimeFormat dateStyle & timeStyle` [polyfill](https://www.npmjs.com/package/@formatjs/intl-datetimeformat) and `formatRange` but cannot edit. What's the new process?

**Comment by jswalden** [comment]
Something got changed a couple few months back permissions-wise, and possibly literally everyone was locked out of editing it for some period of time.  @sffc readded a bunch of people at start of one of the monthly meetings when people brought it up, so he's the one you want to talk to.

**Comment by ljharb** [comment]
Currently delegates have “triage”, and push access is needed to edit the wiki.

**Comment by sffc** [comment]
Accept your invite here and then you should have edit rights restored:

https://github.com/tc39/ecma402/invitations

**Comment by longlho** [comment]
thanks a lot @sffc
