### ISSUE TITLE
PartitionDateTimePattern reads invalid [[TimeZoneName]] slot from ToLocalTime result

### ISSUE THREAD

**Issue by Ms2ger** [tc39/ecma402#515]
PartitionDateTimePattern has:

> 1. Let _tm_ be ToLocalTime(_x_, _dateTimeFormat_.[[Calendar]], _dateTimeFormat_.[[TimeZone]]).
> 1. For each element _patternPart_ of _patternParts_, in List order, do
>     1. Let _p_ be _patternPart_.[[Type]].
>     1. Else if _p_ matches a Property column of the row in Table 6, then
>         1. Let _v_ be the value of _tm_'s field whose name is the Internal Slot column of the matching row.

Table 6 has an entry for [[TimeZoneName]], but ToLocalTime returns a record with the fields listed in Table 7, and [[TimeZoneName]] isn't one of them.

**Comment by longlho** [comment]
Hmm this seems fine? At least in our implementation the relevant field when it comes to determining `TimeZoneName` is `tm[[InDST]]`. In this case `v` would just be unused (& `undefined`).

**Comment by Ms2ger** [comment]
Hmm, I don't know that we're usually in the habit of reading slots that aren't there and treating them as undefined.

**Comment by Yazeed0712** [comment]
https://github.com/AppStoreFoundation/asf-wallet-android

**Comment by ryzokuken** [comment]
This has been fixed in #573. Thanks @Ms2ger for reporting this, @FrankYFTang for fixing it and @romulocintra for noticing that it wasn't closed.
