### ISSUE TITLE
Discuss new CI options

### ISSUE THREAD

**Issue by leobalter** [tc39/ecma402#522]
Travis-CI hasn't been welcoming for our current PRs. 

I'd like to migrate our CI work to GitHub Actions but I'm open to other suggestions.

We need to preserve our current PR builds and the build on the master branch that pushes the spec text to gh-pages.

**Comment by ljharb** [comment]
Github Actions are what 262 is planning to move to (https://github.com/tc39/ecma262/pull/2260).

**Comment by leobalter** [comment]
Thanks for the link. My preference is to reuse the same for consistency.
