### ISSUE TITLE
Rework spec text in 9.2.8: SupportedLocales (availableLocales, requestedLocales, options) to link to the abstract operations

### ISSUE THREAD

**Issue by caridy** [tc39/ecma402#53]
![image](https://cloud.githubusercontent.com/assets/38969/11159233/df209de8-8a2b-11e5-992f-1b1b04be3180.png)

there isn't a notion of an abstract op as a value, instead we should just call the corresponding abstract directly in the then or the else.

**Comment by rwaldron** [comment]
I'm not sure "invalid" is a correct assessment—there is no rule preventing mechanisms such as this.

**Comment by caridy** [comment]
update the title to reflect that what we want is to link to those abstract operations, @bterlson recommendation is to not use the op as a value.

**Comment by rwaldron** [comment]
Ok, that's fine then

**Comment by bterlson** [comment]
Upon reflection I think it's probably fine and understandable, but maybe would require an update to 5.2 to mention that style of usage?

**Comment by rwaldron** [comment]
Sounds good, thanks @bterlson
