### ISSUE TITLE
The spec was not build and sync with the tree after 2021-02-11

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#542]
I notice none of the commit after
Create notes-2021-02-11.md 8488eb7856298dee86d8e2f9de049841805e87f9
got build successfully and sync into https://tc39.es/ecma402/

For example, the following are not in there
spec: GetOption reform for ECMA 2021 (#538) … @ryzokuken  
Normative: Adding Intl.DateTimeFormat formatRange/formatRangeToParts … @fabalbon
Normative: Use OrdinaryHasInstance in normative optional steps (#500) @shvaikalesh
Do not allow duplicate variants within the tlang component of a trans… … @jswalden

@ryzokuken, @fabalbon  @shvaikalesh , @sffc , @jswalden 

It break start on https://github.com/tc39/ecma402/runs/1923390814

**Comment by ljharb** [comment]
ah, github stopped supporting short SHAs.

**Comment by ljharb** [comment]
#543 should fix that.

**Comment by sffc** [comment]
I take that this is fixed.
