### ISSUE TITLE
Undefined behavior of NumberFormat with specified locale

### ISSUE THREAD

**Issue by yanickrochon** [tc39/ecma402#545]
I came across this undefined behavior :

1. Browser **Firefox** with `navigator.language = "en-US";`

```js
console.log( navigator.language );
// -> "en-CA"
console.log( new Intl.NumberFormat('fr-CA', { style: 'currency', currency: 'CAD' }).format(1) );
// -> "1,00 $"
```

2. Browser **Chrome** with `navigator.language = "fr"`;

```js
console.log( navigator.language );
// -> "fr"
console.log( new Intl.NumberFormat('fr-CA', { style: 'currency', currency: 'CAD' }).format(1) );
// -> "1,00 $ CA"
```

Both scripts are expected to output `"1.00 $"` because both specified locales specify the same country code (`CA`) and using the same currency code (`CAD`), therefore the country code should not be displayed. The behavior is correct in the first, but wrong in the second.

There is no difference between both script, except that `nagivator.language` return different values, and I have not read that the specification relies on that value when a locale is specified. Both `Intl.NumberFormat` instances are created with the same locale and the same options, however `format` returns different values in both browsers.

The expected behavior would be that the same script, using the same explicit arguments, including a specific locale, should produce the same output, regardless of the default locale.

If the script would _not_ provide a specific locale, then it would depend on the default locale, therefore the output would depend on the environment, however the `locale` argument is explicitly defined, yet the class behaves differently, ignored the specified locale.

**Comment by zbraniecki** [comment]
The output of Intl formatter is best effort and may and will change between versions and engines. 

If you believe Firefox can improve the output, file in bugzilla.mozilla.org

**Comment by yanickrochon** [comment]
Then it _is_ a bug! Out of curiosity, I tried changing my locale on Chrome ("fr-CA", "en-US", "en-CA", etc.); all of them got the wrong expected output.

In short, the spec is not specifying what happens when a country code is provided with the locale.

Expected behavior : when a currency and a locale with the same country code is provided, the symbol should not display the country of the currency.

**Comment by zbraniecki** [comment]
> Then it is a bug! 

No, the spec does not claim that in `CA` locale `CAD` should be omitted. This is not mandated by the spec.

> In short, the spec is not specifying what happens when a country code is provided with the locale.

Exactly. And it will not because it is best-effort. You provide data and all the ECMA-402 guarantees is that the output will be an attempt to provide the most appropriate representation of the input in the locale.

If you think that a particular engine can improve (I misread your preference), please report the bug against that browser. (in your case it seems like you're saying that you'd like to see V8 to improve their output, so file a bug against them).

**Comment by yanickrochon** [comment]
I filed a bug against the V8 engine back in 2011. It still hasn't been resolved.

If it's not in spec, it won't get fixed.

This should be in specs : if the currency's country code is the same as the locale's country code, it should be treated as "narrowSymbol".

**Comment by zbraniecki** [comment]
> This should be in specs : if the currency's country code is the same as the locale's country code, it should be treated as "narrowSymbol".

This is not that simple. Culture codes about currency display are not normalized and are locale dependent. In result localizers who provide CLDR (or other input database) data are the best source of decision on how to display currencies in a given locale.

Arbitrary "hard-coded" assumptions like what you're suggesting are against how internationalization works.

**Comment by sffc** [comment]
Closing this issue since it is not a spec issue. Please file a bug against the browser engines if you think locale data is wrong.

**Comment by anba** [comment]
Firefox is current still using CLDR 37 resources. As soon as we update to CLDR 38, Firefox will show the same output as Chrome. 

Upstream CLDR bug report: https://unicode-org.atlassian.net/browse/CLDR-14440

**Comment by yanickrochon** [comment]
@anba From the text in the link provided :

> 250 CAD in fr-CA should be 250,00 $
> 250 CAD in en-CA should be $250.00
> 250 CAD in fr-FR should be 250,00 $ CA
> 250 CAD in en-US should be Can$250.00/CAN$250.00

This is exactly what I'm describing, here, and from your comment, then Chrome (or the V8 engine) is wrong, and Firefox has the correct implementation. However, if Firefox is to update and output the thing as Chrome, then FIrefox will introduce the same bug.

The problem is with CLDR, then?

**Comment by anba** [comment]
> The problem is with CLDR, then?

Yes, exactly that. It's already too late for the next CLDR release (v39), so we have to wait for the v40 release (scheduled for October) to get this fixed in CLDR. ([CLDR schedule](https://docs.google.com/spreadsheets/d/1N6inI5R84UoYlRwuCNPBOAP7ri4q2CmJmh8DC5g-S6c/edit#gid=1680747936))

**Comment by sffc** [comment]
In case it's helpful: you can see the symbol for CAD on a locale-by-locale basis from here:

https://unicode-org.github.io/cldr-staging/charts/latest/by_type/currencies.north_america__c_.html#1b135ed4505572d6

**Comment by yanickrochon** [comment]
> Yes, exactly that. It's already too late for the next CLDR release (v39), so we have to wait for the v40 release (scheduled for October) to get this fixed in CLDR. ([CLDR schedule](https://docs.google.com/spreadsheets/d/1N6inI5R84UoYlRwuCNPBOAP7ri4q2CmJmh8DC5g-S6c/edit#gid=1680747936))

@anba do you know where issues can be submitted? The schedule indicates that we are in the submission period, but the Github repository has no issue tracking.

**Comment by srl295** [comment]
For reference: [CLDR-15189](https://unicode-org.atlassian.net/browse/CLDR-15189) links here.
