### ISSUE TITLE
Change to main branch

### ISSUE THREAD

**Issue by sffc** [tc39/ecma402#555]
Follow-up from monthly meeting.

**Comment by ryzokuken** [comment]
@leobalter are you still working on this?

@ljharb is there a documented TC39-wide procedure for this?

**Comment by ljharb** [comment]
It's pretty straightforward - I'm happy to do it once 402 editors have agreed.

**Comment by ryzokuken** [comment]
@ljharb I believe there is a consensus within TG2 based on https://github.com/tc39/ecma402/issues/555#issue-829422610 but just in case, can you confirm @gibson042 @leobalter?

**Comment by gibson042** [comment]
Confirmed.

**Comment by ben-allen** [comment]
Closed as complete!
