### ISSUE TITLE
[Discussion] find a unicode symbol to replace `[[&lt;_key_&gt;]]` mechanism in the 3rd edition

### ISSUE THREAD

**Issue by caridy** [tc39/ecma402#56]
/cc @rwaldron @bterlson

**Comment by caridy** [comment]
This form will most likely disappear when we introduce `formatToParts`, since we will not longer use the loop over table 3. I will keep this around just in case.

**Comment by caridy** [comment]
Update: this one is kinda die-hard! We still use it in few places, hopefully something we can eliminate in 5th Edition. I'm optimistic :)

**Comment by caridy** [comment]
We are half way there, @anba made tons of changes to eliminate the usage from ECMAScript Objects. The remaining work is to remove the usage of this notation on Records.

**Comment by spectranaut** [comment]
I'm tempted to close this issue, as the `[[&lt;_key_&gt;]]` notation and mechanism has become common practice in ECMA-402. It's slightly annoying to write/edit, but pretty easy to read.

What do you think @leobalter?

**Comment by littledan** [comment]
I agree with @spectranaut ; I'd be in favor of closing this. It'd be much less clear to change to some other mechanism (e.g., objects, or a list of key/value pairs).

**Comment by caridy** [comment]
I'm good with that too @spectranaut
