### ISSUE TITLE
Editorial- Unify the option value calendar/collation/numberingSystem checking while referring to UTS35

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#565]
This issue is discovered by @ryzokuken  while he is reviewing https://github.com/tc39/intl-displaynames-v2 but I think the issue is in the current ECMA402 text itself

https://tc39.es/ecma402/#sec-initializedatetimeformat
7.a. If calendar does not match the Unicode Locale Identifier type nonterminal, throw a RangeError exception.
10. a. If numberingSystem does not match the Unicode Locale Identifier type nonterminal, throw a RangeError exception.

https://tc39.es/ecma402/#sec-initializenumberformat
7.a. If numberingSystem does not match the Unicode Locale Identifier type nonterminal, throw a RangeError exception.

https://tc39.es/ecma402/#sec-initializecollator
11.a. If collation does not match the Unicode Locale Identifier type nonterminal, throw a RangeError exception.

https://tc39.es/ecma402/#sec-InitializeRelativeTimeFormat
7.a. If numberingSystem does not match the type sequence (from UTS 35 Unicode Locale Identifier, section 3.2), throw a RangeError exception.

https://tc39.es/ecma402/#sec-Intl.Locale
14.a. If calendar does not match the type sequence (from UTS 35 Unicode Locale Identifier, section 3.2), throw a RangeError exception.
17.a. If collation does not match the type sequence (from UTS 35 Unicode Locale Identifier, section 3.2), throw a RangeError exception.
27.a. If numberingSystem does not match the type sequence (from UTS 35 Unicode Locale Identifier, section 3.2), throw a RangeError exception.

**Comment by ryzokuken** [comment]
Perfect, thanks Frank.

**Comment by sffc** [comment]
Related: #395.  I think we should consider making a table of calendars like we have for units, date fields, numbering systems, and other things.
