### ISSUE TITLE
CLDR logic for PLURALs (number+noun) is different for Czech from Russian and Polish

### ISSUE THREAD

**Issue by JitkaAd** [tc39/ecma402#570]
For some reason, the structure of individual options for plural in the CLDR standard published in GIT differs in Czech from other Slavic languages like Russian and Polish, though the grammar in those languages is very similar and before CLDR they were in synch.

Russian has options mapped as further: one#1, few#2-4, many#5+, other#decimal, in Czech the last two are swapped many is for decimal and other for the big plural 5+ (see the links to specs below). Is there any reason to have it handled different, because from outside it looks like someone made a mistake during the specification phase.

Since we do not need the decimal option there all the time, we have to treat different languages differently by our validation script - for Russian it is ok when Other is missing, for Czech it is okay when Many is missing. Quite a mess.

https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#cs
https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#ru

**Comment by zbraniecki** [comment]
Please, report it against CLDR. ECMA-402 is an API that can be implemented in many different ways and backed by different data sources. CLDR is just a reference one we suggest, but we are not in control of its data.

**Comment by JitkaAd** [comment]
@zbraniecki would you know how to do that, this was a first place I was able to report anything?

**Comment by sffc** [comment]
You can file a CLDR issue by making an account on https://unicode-org.atlassian.net/.

**Comment by JitkaAd** [comment]
Thanks, and here https://unicode-org.atlassian.net/browse/CLDR-14692
