### ISSUE TITLE
Add "Properties of Intl.Locale Instances" section

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#574]
There should be a "Properties of Intl.Locale Instances" section describing the internal slots and default prototype of `Intl.Locale` objects.

**Comment by FrankYFTang** [comment]
+1

**Comment by FrankYFTang** [comment]
@ben-allen @sffc - I think this one should be not hard to do for Ben and should be not controversial

**Comment by FrankYFTang** [comment]
Here are some ref in the spec of other Intl Objects
10.4 Properties of Intl.Collator Instances
https://tc39.es/ecma402/#sec-properties-of-intl-collator-instances

11.4 Properties of Intl.DateTimeFormat Instances
https://tc39.es/ecma402/#sec-properties-of-intl-datetimeformat-instances

12.4 Properties of Intl.DisplayNames Instances
https://tc39.es/ecma402/#sec-properties-of-intl-displaynames-instances

13.4 Properties of Intl.ListFormat Instances
https://tc39.es/ecma402/#sec-properties-of-intl-listformat-instances

15.4 Properties of Intl.NumberFormat Instances
https://tc39.es/ecma402/#sec-properties-of-intl-numberformat-instances

16.4 Properties of Intl.PluralRules Instances
https://tc39.es/ecma402/#sec-properties-of-intl-pluralrules-instances

17.4 Properties of Intl.RelativeTimeFormat Instances
https://tc39.es/ecma402/#sec-properties-of-intl-relativetimeformat-instances

18.4 Properties of Intl.Segmenter Instances
https://tc39.es/ecma402/#sec-properties-of-intl-segmenter-instances

18.5.3 Properties of Segments Instances
https://tc39.es/ecma402/#sec-properties-of-segments-instances

18.6.3 Properties of Segment Iterator Instances
https://tc39.es/ecma402/#sec-properties-of-segment-iterator-instances

Currently in 14.1.1 Intl.Locale ( tag [ , options ] )
https://tc39.es/ecma402/#sec-Intl.Locale
It referred to some internal slots without define them as needed 

```
3. Let internalSlotsList be « [[InitializedLocale]], [[Locale]], [[Calendar]], [[Collation]], [[HourCycle]], [[NumberingSystem]] ».
4. If relevantExtensionKeys contains "kf", then
a. Append [[CaseFirst]] as the last element of internalSlotsList.
5. If relevantExtensionKeys contains "kn", then
a. Append [[Numeric]] as the last element of internalSlotsList.
```

and
```
30. Set locale.[[Locale]] to r.[[locale]].
31. Set locale.[[Calendar]] to r.[[ca]].
32. Set locale.[[Collation]] to r.[[co]].
33. Set locale.[[HourCycle]] to r.[[hc]].
34-a. Set locale.[[CaseFirst]] to r.[[kf]].
35-a-i. Set locale.[[Numeric]] to true.
35-b-i. Set locale.[[Numeric]] to false.
36. Set locale.[[NumberingSystem]] to r.[[nu]].
```
so the internal slots should have at least these 7 slots mentioned.

**Comment by sffc** [comment]
TG2 discussion: https://github.com/tc39/ecma402/blob/master/meetings/notes-2023-05-04.md#add-properties-of-intllocale-instances-section
