### ISSUE TITLE
Lower case mapping definition missing in 6.1

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#576]
@anba found this issue while reviewing Intl.DisplayNames v2 (see https://github.com/tc39/intl-displaynames-v2/issues/37 )  but I think the issue is introduced in v1 and already part of ECMA402, so I file this issue here and we need a PR to address ECMA402 itself.

https://tc39.es/ecma402/#sec-canonicalcodefordisplaynames
"
3-b. Let code be the result of mapping the first character in code to upper case, and mapping the second, third, and fourth character in code to lower case, as described in 6.1.
"

https://tc39.es/ecma402/#sec-case-sensitivity-and-case-mapping
"The String values used to identify locales, currencies, and time zones are interpreted in a case-insensitive manner, treating the Unicode Basic Latin characters "A" to "Z" (U+0041 to U+005A) as equivalent to the corresponding Basic Latin characters "a" to "z" (U+0061 to U+007A). No other case folding equivalences are applied. When mapping to upper case, a mapping shall be used that maps characters in the range "a" to "z" (U+0061 to U+007A) to the corresponding characters in the range "A" to "Z" (U+0041 to U+005A) and maps no other characters to the latter range."

**Comment by ryzokuken** [comment]
Since the attached PR was merged, closing this. Feel free to reopen.
