### ISSUE TITLE
Add a number parser for parsing numbers using non-latin numerals

### ISSUE THREAD

**Issue by kevinbarabash** [tc39/ecma402#579]
Some languages use different numerals, e.g. [Eastern Arabic](https://en.wikipedia.org/wiki/Eastern_Arabic_numerals) numerals and [Georgian numerals](https://en.wikipedia.org/wiki/Georgian_numerals) (amongst others).  It would be nice to have some way to parse these built into the browser.

**Comment by Yaffle** [comment]
You can use html for this : `<input type="number" value="ჩ" lang="en-u-nu-geor" />`  - in Firefox the value property will return the number somehow.
Why cannot this be done in JavaScript? It is not difficult to do the conversion for all decimal numbers.

**Comment by ryzokuken** [comment]
Localized string parsing is a non-goal for ECMA-402. For more, see #1 and https://blog.sffc.xyz/post/190943794505/why-you-should-not-parse-localized-strings.

**Comment by sffc** [comment]
This makes sense within the scope of a unicode properties API.

Closing this issue in favor of https://github.com/tc39/ecma402/issues/90.
