### ISSUE TITLE
[Spec Bug] Requested options should expand best match options in DateTime Format

### ISSUE THREAD

**Issue by caridy** [tc39/ecma402#58]
### Background

From the algo described in "2.6.2 Elements availableFormats, appendItems", it seems that the requested options should have a leading role when formatting the best match pattern. Below is the relevant section:

================

http://unicode.org/reports/tr35/tr35-dates.html#availableFormats_appendItems

Once a skeleton match is found, the corresponding pattern is used, but with adjustments. Consider the following dateFormatItem:

```xml
    <dateFormatItem id="yMMMd">d MMM y</dateFormatItem>
```

If this is the best match for yMMMMd, pattern is automatically expanded to produce the pattern "d MMMM y" in response to the request. Of course, if the desired behavior is that a request for yMMMMd should produce something other than "d MMMM y", a separate dateFormatItem must be present, for example:

```xml
    <dateFormatItem id="yMMMMd">d 'de' MMMM 'de' y</dateFormatItem>
```

=================

### The Problem

402 does not consider the requested options as part of the resolvedOptions, instead, it only uses the required options to find the best match. In algo [12.1.1 InitializeDateTimeFormat (dateTimeFormat, locales, options)](https://tc39.github.io/ecma402/#sec-InitializeDateTimeFormat), in step __26.c.1__, `Set dateTimeFormat.[[<prop>]] to p.`, it stores the output option in an internal slot (e.g.: "long" for "{month}") from the format returned from best match algo, the proposal is to overruling that with the value of property "month" from requested options if exist, as described in unicode documentation cited above.

This issue is the major source of problems in Intl.js (Intl polyfill issues: 125, 117, 124, 145 and co.).

**Comment by caridy** [comment]
Here is the diff in the polyfill:

```
@@ -1935,7 +1935,9 @@ function/* 12.1.1.1 */InitializeDateTimeFormat (dateTimeFormat, locales, options
                 p = bestFormat[prop];

             // ii. Set the [[<prop>]] internal property of dateTimeFormat to p.
-            internal['[['+prop+']]'] = p;
+            // Diverging from spec because of bug #58
+            // https://github.com/tc39/ecma402/issues/58
+            internal['[['+prop+']]'] = opt['[['+prop+']]'] || p;
         }
```

**Comment by rxaviers** [comment]
I'm ccing @JCEmmons, who has implemented this for ibm-js/ecma402 if I'm not wrong, and could have input.

**Comment by srl295** [comment]
@caridy going to have to come back to this…

**Comment by littledan** [comment]
For what it's worth, V8 follows the ICU algorithm, rather than the spec, here. It seems like Firefox does as well.

**Comment by caridy** [comment]
Further investigation reveal that `BasicFormatMatcher` doesn't have enough information to enforce the extra rule described here, which is fine, since this is the bare minimum required for this implemention, while `BestFitFormatMatcher()` can certainly take that into consideration. Closing.

**Comment by jpresley23** [comment]
Is there a workaround for this? I'm running an issue where we use react-intl but I need Intl.js polyfill for PhantomJS for our tests. If I use Intl.js version 1.1.0, the leading zero in the minutes is dropped off. If I use 1.0.1, the leading 0 for "00:00" is dropped (it's rendered as "0:00").
