### ISSUE TITLE
DateFormat('yyyyMMdd') not work but DateFormat('yyyy-MM-dd') dose

### ISSUE THREAD

**Issue by johnwangwjq** [tc39/ecma402#582]
Hi, thanks for the nice package.

However `DateFormat('yyyyMMdd').parse('20210521')` will throw the following error:

```
Unhandled exception:
FormatException: Trying to read MM from 20210521 at position 8
...
```
But  `DateFormat('yyyy-MM-dd').parse('2021-05-21')` works,

even 

`DateFormat('yyyy 年 MM 月 dd 日').parse('2021 年 05 月 21 日')` does.

What have I missed? Is it mandatory that a pattern string have seperators charactors between the time fields?

**Comment by sffc** [comment]
Hi @johnwangwjq, this repository is for issues related to the `Intl` object in ECMAScript.  We do not have a type named `DateFormat` and we do not support any `.parse()` functions.  I suspect you filed this issue in the wrong project.
