### ISSUE TITLE
ships the entire payload requirement

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#586]
This is a moving of issue from 
https://github.com/tc39/proposal-intl-enumeration/issues/31
to ECMA402

During the Intl Enumeration API Stage 2 update discussion in TC39 May 2021 meeting, we received a feedback "entire payload requirement" issue

Based on https://github.com/tc39/proposal-intl-enumeration/issues/31#issuecomment-859978625
and
https://github.com/tc39/proposal-intl-enumeration/issues/31#issuecomment-860022343
I move the issue to "a general ECMA-402 issue" so we can act separately

**Comment by ljharb** [comment]
If you prefer, we can transfer the issue directly here.

**Comment by FrankYFTang** [comment]
ok, close this one then....
