### ISSUE TITLE
Remove "minInteger" parameter from ToRawFixed

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#589]
The "minInteger" parameter to [ToRawFixed](https://tc39.es/ecma402/#sec-torawfixed) is unused and only 1 of 3 callers pass the parameter, i.e. [PartitionNotationSubPattern](https://tc39.es/ecma402/#sec-partitionnotationsubpattern) should also be updated to not pass "minInteger".

**Comment by anba** [comment]
@sffc This issue also affects the diff for "Intl.NumberFormat V3".

**Comment by ryzokuken** [comment]
@sffc @anba this issue is fixed by the current version for NFv3. Should we close this or keep it open until the proposal is Stage 4? In that case, should we use some sort of label to make sure we remember to close it later?

**Comment by sffc** [comment]
The issue is assigned to me and labeled "in progress".

**Comment by anba** [comment]
Closing. This issue has been fixed at some point.
