### ISSUE TITLE
9.2.5 ResolveLocale 13.f.ii only considers zero or one 'type' subtag

### ISSUE THREAD

**Issue by thetalecrafter** [tc39/ecma402#59]
ResolveLocale cannot accept some valid calendars in a `u-ca-` extension, because it only considers a `key` subtag followed by zero or one `type` subtags. [RFC 6067](https://tools.ietf.org/html/rfc6067) allows for "zero or more" `type` subtags to make the `keyword`.

In the current spec the following [calendar identifiers](http://www.unicode.org/repos/cldr/tags/latest/common/bcp47/calendar.xml) are incorrectly matched:
* `ethiopic-amete-alem` is an alias for `ethioaa`, but will be matched as `ethiopic`.
* `islamic-civil` replaces the deprecated `islamicc`, but will be matched as `islamic`.
* `islamic-umalqura`, `islamic-tbla`, and `islamic-rgsa` will each be matched as `islamic`.

**Comment by thetalecrafter** [comment]
Thanks @caridy!

**Comment by jungshik** [comment]
Has a test been added for this? An indirect test would be possible with by checking the value of 'calendar' option. For instance, something like this can be used to test. 

```
 var options = Intl.DateTimeFormat("ar-u-ca-islamic-civil").resolvedOptions();
 assertEquals(options.calendar, "islamic-civil");
```
