### ISSUE TITLE
Publish an html version of the 2.0 specification

### ISSUE THREAD

**Issue by Elchi3** [tc39/ecma402#61]
The 1.0 specification is available
http://www.ecma-international.org/ecma-402/1.0/
but there is no html version for 2.0
http://www.ecma-international.org/ecma-402/2.0/

Thanks for putting the current draft (3.0) on GitHub pages :+1: 
(referencing and deeplinking specs is just nicer with html)

**Comment by caridy** [comment]
the html version will be published soon, in the meantime, you can download it from here: https://github.com/tc39/ecma402/releases/tag/2.0
