### ISSUE TITLE
Clarify types of fields in result of ToLocalTime

### ISSUE THREAD

**Issue by Ms2ger** [tc39/ecma402#619]
FormatDateTimePattern handles the fields as if they contain mathematical values:

> 13. Let tm be ToLocalTime(x, dateTimeFormat.[[Calendar]], dateTimeFormat.[[TimeZone]]).
>
> ...
>
> i. Let v be tm.[[Millisecond]].
> ii. Let v be floor(v × 10( fractionalSecondDigits - 3 )).
>
> ...
>
> iii. Let v be the value of tm's field whose name is the Internal Slot column of the matching row.
> iv. If p is "year" and v ≤ 0, let v be 1 - v.

and similar things happen in PartitionDateTimeRangePattern. However, ToLocalTime says that, for example, [[Weekday]] is defined as

> WeekDay(tz) specified in es2022's [Week Day](https://tc39.es/ecma262/#sec-week-day)

which explicitly returns a Number.

**Comment by ben-allen** [comment]
Closed as fixed by a45c0f9964e1d7e2cadc598ae7024d90b8c4b866
