### ISSUE TITLE
Add support for arbitrary code inside template tags

### ISSUE THREAD

**Issue by manuel-di-iorio** [tc39/ecma402#63]
Why not support any arbitrary code inside template strings expressions?

This is not supported i.e:

    `${ if (a == 2) {
        console.log('hi');
    } }`

And with more complex code, like if, if-else, for loops, etc..

It would be nice to develop a template engine that uses this native approach instead of a string manipulation.

**Comment by caridy** [comment]
@manuel-di-iorio template literals are not part of ecma402, but tc39/ecma262, my recommendation is to start a new discussion via https://esdiscuss.org/1
