### ISSUE TITLE
Inline GetOperands into PluralRuleSelect

### ISSUE THREAD

**Issue by gibson042** [tc39/ecma402#635]
Following up on #594, I'd like to inline [GetOperands](https://tc39.es/ecma402/#sec-getoperands) into [PluralRuleSelect](https://tc39.es/ecma402/#sec-pluralruleselect), replacing the Record _operands_ parameter of the latter with the String that is currently input of the former ([[FormattedString]] output from [FormatNumericToString](https://tc39.es/ecma402/#sec-formatnumberstring)). The implementation-defined behavior of PluralRuleSelect would still have access to what is now the input of GetOperands and could deconstruct it in that way if/when appropriate.
```patch
         1. Let _res_ be ! FormatNumericToString(_pluralRules_, _n_).
-        1. Let _s_ be _res_.[[FormattedString]].
-        1. Let _operands_ be ! GetOperands(_s_).
-        1. Return ! PluralRuleSelect(_locale_, _type_, _n_, _operands_).
+        1. Return ! PluralRuleSelect(_locale_, _type_, _n_, _res_.[[FormattedString]]).
```

We might also be able to remove the Number _n_ parameter of PluralRuleSelect, but only if implementations are required to select the same plural category for distinct numbers that format identically, such as `"one"` for `1.01` when rounding options format it as `"1"` (which I *think* is the case but would need confirmation):
```
        1. Return ! PluralRuleSelect(_locale_, _type_, _res_.[[FormattedString]]).
```

**Comment by ben-allen** [comment]
I'm reading through these older issues -- do you think this one is still worth pursuing?

@gibson042

**Comment by gibson042** [comment]
Yes. It's weird that ResolvePlural takes in a number, formats it to a string, calls out to a dedicated GetOperands operation (_i.e., called from nowhere else_) for deconstructing that string and reconstructing a number value for it, and then passes the resulting Record to an opaque implementation-defined PluralRuleSelect operation. Because PluralRuleSelect is opaque, implementations already have the freedom to perform the steps of GetOperands within it as warranted.

**Comment by sffc** [comment]
TG2 discussion: https://github.com/tc39/ecma402/blob/main/meetings/notes-2024-08-22.md#inline-getoperands-into-pluralruleselect
