### ISSUE TITLE
References to Unicode documents are unnecessarily inconsistent

### ISSUE THREAD

**Issue by gibson042** [tc39/ecma402#640]
ECMA-402 makes many references to Unicode documents, but does so inconsistently:
```sh
$ grep --no-filename -ro 'U[[:alpha:]]* *[A-Z][[:alpha:]]* *[A-Z][[:alpha:]]* *#*[0-9][0-9]*' spec/ | sort | uniq -c
     12 Unicode BCP 47
      1 Unicode Technical Standard 10
     15 Unicode Technical Standard 35
     12 Unicode Technical Standard #35
     14 UTS 35
      6 UTS #35
```

It would be better to uniformly adopt a consistent pattern. Unicode itself appears to prefer expanded spellings with number sign, as visible at e.g. https://unicode.org/glossary/ .

**Comment by ben-allen** [comment]
Is this one still open? Currently the only occurrence of irregular references is in a table heading where changing from UTS would result in awkward rendering.

**Comment by gibson042** [comment]
I guess it's done!

**Comment by ben-allen** [comment]
While I was poking at this I realized that there's several references to Unicode Technical Standard #35 that don't provide:
1) references to the applicable portion of the standard
