### ISSUE TITLE
Incorrect currency display for TWD via Intl.NumberFormat

### ISSUE THREAD

**Issue by JustJenFelice** [tc39/ecma402#642]
**Description:** 
Running `new Intl.NumberFormat('zh-TW', { style: 'currency', currency: 'TWD' }).format(12345.67)"` should return `NT$12,345.67`

**eshost Output:**

```
$ eshost -s -e "new Intl.NumberFormat('zh-TW', { style: 'currency', currency: 'TWD' }).format(12345.67)"
#### ChakraCore, JavaScriptCore, SpiderMonkey, V8
$12,345.67
```

**Comment by sffc** [comment]
The observed behavior is consistent with CLDR data.  You can find the currency symbols here:

https://unicode-org.github.io/cldr-staging/charts/latest/by_type/currencies.eastern_asia__c_.html#1b51c5cbac96e731

TWD-symbol | English: ‹NT$›
-- | --
$ | ·zh_Hant·
NT$ | ·be_TARASK· ·eo· ·nds· ·zh_Hant_HK· ·all·others·
TWD | ·bg· ·br· ·en_AU· ·es· ·es_419· ·fi· ·fr· ·fr_CA· ·hr· ·hu· ·is· ·it· ·kab· ·ky· ·lt· ·mk· ·nn· ·no· ·pl· ·ro· ·sk· ·sl· ·sv· ·uk·

You may want the "formal" variant of the currency symbol, which uses "NT$" for all regions, including TW.  I opened #643 to track that feature request.
