### ISSUE TITLE
Forbid underscores in DisplayNames identifiers

### ISSUE THREAD

**Issue by sffc** [tc39/ecma402#646]
Follow-up from https://github.com/tc39/ecma402/projects/2#card-68491050

We discussed in the 2022-01-13 meeting whether we should accept underscores in DisplayNames, in response to https://github.com/tc39/test262/pull/3173/files.  We decided that we should reject the underscores, and @FrankYFTang is going to follow up with a PR to enforce this in the spec.

Discussion notes: https://github.com/tc39/ecma402/blob/master/meetings/notes-2022-01-13.md#should-we-accept-_-in-identifiers

**Comment by FrankYFTang** [comment]
PR is already reviewed in https://github.com/tc39/ecma402/pull/647

**Comment by sffc** [comment]
Confirmed that this appears to have been fixed by #647
