### ISSUE TITLE
PartitionNumberPattern fails to properly handle mathematical values vs. Number/BigInt

### ISSUE THREAD

**Issue by gibson042** [tc39/ecma402#648]
cf. https://github.com/tc39/ecma402/pull/645#r784295285

> FormatNumericToString expects a Number or BigInt value, while _x_ is a mathematical value that AFAICT might suffer output-affecting lossiness if converted.
> 
> And similar problems in later steps (in which whether or not _x_ is a mathematical value is dependent upon whether or not the original input was finite!)
> 
> …
> 
> I think the best fix would be updating FormatNumericToString/GetNumberFormatPattern/PartitionNotationSubPattern/etc. to accept new parameters allowing them to identify special non-mathematical Number values such as negative zero and infinities and NaN.

**Comment by gibson042** [comment]
https://github.com/tc39/ecma402/pull/651#pullrequestreview-869935114

> I don't think this holds up unless the scope is expanded to properly fix #648, because _many_ related operations are incoherent in the same way:
> * [FormatNumeric](https://tc39.es/ecma402/#sec-formatnumber) is documented to accept <var>x</var> (which must be a Number or BigInt value), but FormatDateTimePattern incorrectly invokes it with mathematical values.
> * FormatNumeric then sends it to PartitionNumberPattern, which also expects <var>x</var> (a Number or a BigInt).
> * PartitionNumberPattern handles finite <var>x</var> by sending it to ComputeExponent (which implicitly and incorrectly treats it as a mathematical value and returns a mathematical value) and FormatNumericToString, replacing <var>x</var> with the [[RoundedNumber]] slot of the record returned by FormatNumericToString.
>   * FormatNumericToString accepts <var>x</var> (which must be a Number or BigInt value), but incorrectly performs some operations upon it that are only valid with mathematical values. It replaces <var>x</var> with a mathematical value from the [[RoundedNumber]] slot of a record returned by either ToRawPrecision or ToRawFixed, and then returns either that mathematical value or its negation in [[RoundedNumber]].
> * Back in PartitionNumberPattern, <var>x</var> could be either the supposedly Number/BigInt input **or** a mathematical value from FormatNumericToString.
> * PartitionNumberPattern sends <var>x</var> to GetNumberFormatPattern, which performs some operations upon it that are only valid for mathematical values and others that can only succeed if it is a Number.
> * PartitionNumberPattern then sends the type-confused <var>x</var> to PartitionNotationSubPattern, the current object of this PR, which expects <var>x</var> (which is a numeric value after rounding is applied) and is sufficiently vague in its treatment that no further specification seems required.

**Comment by anba** [comment]
#822 should fix this issue.
