### ISSUE TITLE
Intl.DisplayNames doesn't work for Polish regions on mobile

### ISSUE THREAD

**Issue by mitow7821** [tc39/ecma402#657]
Demo: (1st line, change locale to 'pl')
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames

I'm using intl displayNames with region option. I've found unexpected behaviour on my mobile device (samsung galaxy a50 - android 11 - chrome). When I use 'pl' locale it returns provided country code instead of translated region.

Desktop:
![image](https://user-images.githubusercontent.com/34492112/157272019-1058ce03-012b-44e4-8718-67e3a3ecf8e1.png)
 
Mobile:
![image](https://user-images.githubusercontent.com/34492112/157272294-10f3926a-3cde-446c-b9dd-ad965934c545.png)

**Comment by sffc** [comment]
Sometimes mobile phone OEMs remove translations from their devices. This is a question for the OEM, not for ECMA-402.

CC @FrankYFTang who has done work on making more locales loadable on the fly in Chrome on Android.

**Comment by FrankYFTang** [comment]
i think this is fixed in https://bugs.chromium.org/p/chromium/issues/detail?id=1097432 do you still have the problem? what is the version of your chrome
