### ISSUE TITLE
Intl.DateTimeFormat() - Hour cycle returns different dateTimeFormat - missing at

### ISSUE THREAD

**Issue by lwelti** [tc39/ecma402#665]
Using:
```js
const date = new Date(Date.UTC(2020, 11, 20, 3, 23, 16, 738));
console.log(new Intl.DateTimeFormat('en-US', { dateStyle: 'full', timeStyle: 'full' }).format(date));
console.log(new Intl.DateTimeFormat('en-US', { dateStyle: 'full', timeStyle: 'full', hourCycle: 'h24' }).format(date));

```
returns:
```js
1) >"Saturday, December 19, 2020 at 7:23:16 PM Pacific Standard Time"
2) >"Saturday, December 19, 2020, 19:23:16 Pacific Standard Time"
```

As you can see for **(2)** is missing the **'at'**

I will expect that is using the **full** dateTime format defined in CLDR: [en](https://github.com/unicode-org/cldr-json/blob/8d565de3afecd4dc3f82b3bdbc3336e2d588a350/cldr-json/cldr-dates-modern/main/en/ca-gregorian.json#L346) which shows:
```js
"full": "{1} 'at' {0}",
```

Please correct me if this is expected or is an 🐛 
thanks in advance

cc @sffc

**Comment by ryzokuken** [comment]
Thanks @anba. Looks like this is fixed and in general, this is an ICU issue and cannot be addressed in this repo, so I'm closing this issue. @lwelti please feel free to reopen it if I'm wrong.

**Comment by anba** [comment]
This is all controlled internally in ICU. I think the relevant ICU 71 bug fix is <https://unicode-org.atlassian.net/browse/ICU-21353> (<https://github.com/unicode-org/icu/pull/1958/>).

**Comment by lwelti** [comment]
@anba thanks! is the spidermonkey source code available in order to get familiar of how is making the call, for my general knowledge, thanks in advance

**Comment by anba** [comment]
The relevant parts are probably <https://searchfox.org/mozilla-central/rev/625c3d0c8ae46502aed83f33bd530cb93e926e9f/intl/components/src/DateTimeFormat.cpp#282-323> and <https://searchfox.org/mozilla-central/rev/625c3d0c8ae46502aed83f33bd530cb93e926e9f/intl/components/src/DateTimeFormat.cpp#149-191>.

Basically we're doing this approach:
1. Retrieve the pattern for the requested style.
2. Compute the skeleton string of the resolved pattern.
3. Adjust that skeleton string to use the correct hour symbol.
4. And finally find the best pattern for the adjusted skeleton string.
