### ISSUE TITLE
"15.5.2 Number Format Functions" should be singlar as "Function" not "Functions"

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#674]
The title of 15.5.2 is "15.5.2 Number Format Functions"
https://tc39.es/ecma402/#sec-number-format-functions
 but it is only referring to a single function, not multiple functions. Should we make an editorial change to rename it as 
"15.5.2 Number Format Function" (remove the ending "s") instead?

Also referred in 
https://tc39.es/ecma402/#sec-intl.numberformat.prototype.format

```
a. Let F be a new built-in [function object](https://tc39.es/ecma262/#function-object) as defined in Number Format Functions ([15.5.2](https://tc39.es/ecma402/#sec-number-format-functions)).
```

@sffc @romulocintra @ryzokuken

**Comment by ryzokuken** [comment]
I think this is fine, since it's referring to a special kind/type of function, which happens to be a singleton.

**Comment by ljharb** [comment]
I agree; a set of 1 things can still be described pluralized.

**Comment by FrankYFTang** [comment]
> I agree; a set of 1 things can still be described pluralized.

but.... this is not referring to a SET of 1 things, but only one thing
Read https://tc39.es/ecma402/#sec-number-format-functions
"A Number format function is an anonymous built-in function that has a [[NumberFormat]] internal slot.

When a Number format function F is called with optional argument value, the following steps are taken:

"
Either the section title should be change to singluar, or the description text should be changed to plural. It does not make sense that the section title use Functions but then the description about such "Functions" are using "A function", right?

**Comment by ljharb** [comment]
In practice it’s one thing, but potentially there could be many. The section is describing the characteristics of a category of things. Later, the spec only puts one thing in that category.

**Comment by FrankYFTang** [comment]
Are you saying, that " Number Format Functions" section may include several functions but currently only has one? If so, then we should have a sub section for 
```
A Number format function is an anonymous built-in function that has a [[NumberFormat]] internal slot.

When a Number format function F is called with optional argument value, the following steps are taken:

1. Let nf be F.[[NumberFormat]].
2. [Assert](https://tc39.es/ecma262/#assert): [Type](https://tc39.es/ecma262/#sec-ecmascript-data-types-and-values)(nf) is Object and nf has an [[InitializedNumberFormat]] internal slot.
3. If value is not provided, let value be undefined.
4. Let x be ? [ToNumeric](https://tc39.es/ecma262/#sec-tonumeric)(value).
5. Return ? [FormatNumeric](https://tc39.es/ecma402/#sec-formatnumber)(nf, x).
The "length" property of a Number format function is 1.
```
to identify a particular function of that, right?

**Comment by FrankYFTang** [comment]
Notice that section is under "15.5 Abstract Operations for NumberFormat Objects" so is that a specific AO? or is it for containing multiple AOs but somehow we have only one AO withhout a sub section in it? It is just confusing in term of the naming and structure

**Comment by ljharb** [comment]
I'm just saying in general that it's correct in english to use plurals to describe a set that happens to contain one item.

**Comment by FrankYFTang** [comment]
> I'm just saying in general that it's correct in english to use plurals to describe a set that happens to contain one item.

But this is NOT a case of "a set that happens to contain one item", but rather a section which referring to only one and only one specific function (with clearly defined algorithm) without any subsections under it. So how is your "general case" applicable for this particular case?

**Comment by ljharb** [comment]
That's not how i read it - the phrase "A Number format function" means there can be 0, 1, or N of them, and that the rest of the section describes what their characteristics are if they exist.

Additionally, https://tc39.es/ecma402/#sec-intl.numberformat.prototype.format creates a new one every time it's invoked - so in fact there is not just one, there are potentially infinite such functions.

**Comment by ljharb** [comment]
https://tc39.es/ecma402/#sec-intl.numberformat.prototype.format creates a new one the first time it's invoked *in a single realm* - so in fact there is not just one, there are potentially infinite such functions, just as there are potentially infinite realms.

**Comment by ryzokuken** [comment]
I agree with @ljharb. A future constructor that encapsulates number formatting (perhaps even `DurationFormat`) could potentially create its own number format function. The "number format functions" here describes not a particular instance, but the entire category of such functions.

**Comment by FrankYFTang** [comment]
ok, I see, so you think "function" is referring to an instance of a object type.

**Comment by ryzokuken** [comment]
@FrankYFTang yes, that's exactly the mental model I've worked with since I first encountered this section of the spec.
