### ISSUE TITLE
Replace "{increase,decrease} _alias_ by $value" algorithm steps

### ISSUE THREAD

**Issue by gibson042** [tc39/ecma402#677]
Rather than using "increase _alias_ by $value" or "decrease _alias_ by $value", we should consistently use the more standard "set _alias_ to _alias_ {+,-} $value".

**Comment by bakkot** [comment]
cf https://github.com/tc39/ecma262/pull/1542 and linked issues.

**Comment by johndoe-glitch** [comment]
```

```
