### ISSUE TITLE
ECMA-402 should allow numeric-offset host time zones

### ISSUE THREAD

**Issue by gibson042** [tc39/ecma402#683]
Among other things, this would remove the need for ECMA-402 Temporal to override ECMA-262 DefaultTimeZone.

**Comment by gibson042** [comment]
Affirmed by https://github.com/tc39/ecma262/pull/2781

**Comment by sffc** [comment]
For example:

```
new Intl.DateTimeFormat("en", { timeZoneName: "+01:00" })
```

**Comment by ptomato** [comment]
Feel free to hide this comment afterwards - I think you want `timeZone: '+01:00'` in the code example though?

**Comment by sffc** [comment]
TG2 discussion: https://github.com/tc39/ecma402/blob/master/meetings/notes-2022-12-08.md#ecma-402-should-allow-numeric-offset-host-time-zones-683

Conclusion: Yes, move forward with a PR for this. @gibson042 kindly volunteered to make the PR.

**Comment by justingrant** [comment]
> TG2 discussion: https://github.com/tc39/ecma402/blob/master/meetings/notes-2022-12-08.md#ecma-402-should-allow-numeric-offset-host-time-zones-683
> 
> Conclusion: Yes, move forward with a PR for this. @gibson042 kindly volunteered to make the PR.

@gibson042 - Is there a PR?  Asking because a PR to resolve #741 will likely end up touching the same parts of the spec, so we should coordinate.

**Comment by justingrant** [comment]
> Note, completing this issue should also remove the "If IsTimeZoneOffsetString(_timeZone_) is _true_, throw a _RangeError_ exception." step from Temporal.ZonedDateTime.prototype.toLocaleString.

It's possible that future PRs (I'm working on one now!) may introduce other blocks of offset strings, so doing a full search for `If IsTimeZoneOffsetString` in [intl.html in the Temporal spec](https://github.com/tc39/proposal-temporal/blob/main/spec/intl.html) is probably a good idea.

**Comment by justingrant** [comment]
@gibson042 - are you still on track to have a PR for this issue available for this week's TG2 meeting?

**Comment by gibson042** [comment]
pull request: #788

**Comment by FrankYFTang** [comment]
I need to investigate the cost to make the dft.resolvedOptions().timeZone  return "+01:00"
