### ISSUE TITLE
Numbering/formatting issue in latest spec PDF

### ISSUE THREAD

**Issue by andyearnshaw** [tc39/ecma402#7]
Just noticed this in the official 2nd edition doc linked from the Ecma site.  The numbers go in the following order, 5-a-b, 1-c, 6:

<img width="466" alt="screen shot 2015-07-14 at 11 41 48" src="https://cloud.githubusercontent.com/assets/1826067/8671486/62980540-2a1d-11e5-9e83-67cc8bb7ee72.png">
I think the _1_ here is supposed to be _c_ and the _c_ should be _d_.

**Comment by rwaldron** [comment]
Isn't Microsoft Word awesome? Can you file this in the Ecma-402 bug tracker? I would greatly appreciate that :) https://bugs.ecmascript.org/enter_bug.cgi?product=Internationalization%20-%20ECMA-402

**Comment by andyearnshaw** [comment]
I can and I have :smile: 

https://bugs.ecmascript.org/show_bug.cgi?id=4424

**Comment by rwaldron** [comment]
Thanks again :)
