### ISSUE TITLE
publish ECMA402 biblio to npm

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#710]
Per https://github.com/tc39/ecmarkup/pull/425#issuecomment-1254085705
it will be nice if we can publish ECMA402 biblio to npm  like [262 does](https://github.com/tc39/ecma262/blob/e72a6b2134ab1d545d9014c85a52a5a10d26625f/.github/workflows/publish-biblio.yml)

@bakkot   @leobalter @gibson042 @ryzokuken

**Comment by FrankYFTang** [comment]
@sffc

**Comment by ljharb** [comment]
Tokens are stored at the repo level, not the org level, so we’d need to add the token to this repo - we’d also need to manually publish the first version (which we did for 262 as well); i can help with both of those.

**Comment by ryzokuken** [comment]
Hi @ljharb want to pick this up again? I'd be happy to help in any way you might require :D

**Comment by ljharb** [comment]
whoops, sure :-) let me take a look at it this afternoon.

**Comment by ljharb** [comment]
The `NPM_TOKEN_FOR_TC39_USER` secret is already on the repo (i must have done it back in September 2022), so I think all that's needed is a PR with the workflow and script, and just prior to landing it, I can publish the first version of the package.
