### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Boldgainobu** [tc39/ecma402#712]

**Comment by Boldgainobu** [comment]
https://github.com/tc39/ecma402/issues/712#issue-1385300366

**Comment by Boldgainobu** [comment]
https://github.com/tc39/ecma402/issues/712#issue-1385300366

**Comment by Boldgainobu** [comment]
Bug report #712

**Comment by Boldgainobu** [comment]
> 

> _https://github.com/tc39/ecma402/issues/712#issuecomment-1257382143._

**Comment by ljharb** [comment]
Please stop spamming.
