### ISSUE TITLE
centralize currencies, collations and calendars

### ISSUE THREAD

**Issue by ryzokuken** [tc39/ecma402#720]
Currently, the proposal focuses on enumerating currencies, collations, calendars, numbering systems, units and time zones. 

Out of these, the last three are well-specified: the list of available numbering systems and units is present in the spec, and time zones are specified as all the IANA time zones, which works pretty well.

Unlike the latter, however, the former three are not well specified. If I understand correctly, in the last TC39 meeting, @codehag expressed a concern that this may allow an implementation to return only a subset of the supported values, which I do not think is intended here. Also, as I mentioned above, this is also not internally consistent within the proposal.

I feel that this points to a larger problem in ECMA-402: because we deal with each new proposal one at a time, we may sometimes lose sight of the bigger picture. Let's take currencies as an example: including this proposal, there will be three places where currencies are used in ECMA-402, with both `NumberFormat` and `DisplayNames`. While I'm sure all implementations would like to (and infact do) support the same set of currencies in all three places, it is not mandated by the spec IIUC and I think it should be.

One way to solve this (that I managed to come up with, there might be better ones) would be to store lists of these values in internal slots of the `Intl` object, and normatively require all present (and future) Intl functions to support the entire list from that slot. Mind you, the contents of these lists would still be implementation-defined, but it would ensure that supporting a different set of currencies, for example, in `NumberFormat` than in `DisplayNames` would be a spec violation.

@FrankYFTang @sffc what do you folks think?

**Comment by ryzokuken** [comment]
Reopening

**Comment by sffc** [comment]
We should resolve this once Intl Enumeration API lands.
