### ISSUE TITLE
DateTimeFormat with dateStyle "medium" not working for pt-PT locale

### ISSUE THREAD

**Issue by nobreferreira** [tc39/ecma402#722]
DateTimeFormat using `dateStyle:'medium'` doesn't work correctly with the **pt-PT** locale.
The output is "17/10/2022" and the expected one is "17 de out. de 2022".

```js
console.log(new Intl.DateTimeFormat('pt-PT', { dateStyle: 'medium' }).format(Date.now()));
// Output "17/10/2022"
// Expected output "17 de out. de 2022"
````

**Comment by nobreferreira** [comment]
Closing this issue as it as defined in CLDR `dateFormats` for **pt-PT** locale.

```json
"dateFormats": {
    "full": "EEEE, d 'de' MMMM 'de' y",
    "long": "d 'de' MMMM 'de' y",
    "medium": "dd/MM/y",
    "short": "dd/MM/yy"
},
```

**Comment by romulocintra** [comment]
> Closing this issue as it as defined in CLDR `dateFormats` for **pt-PT** locale.
> 
> ```json
> "dateFormats": {
>     "full": "EEEE, d 'de' MMMM 'de' y",
>     "long": "d 'de' MMMM 'de' y",
>     "medium": "dd/MM/y",
>     "short": "dd/MM/yy"
> },
> ```

In case you find that this does not reflect the Portuguese reality please open [Issue](https://unicode-org.atlassian.net/jira/software/c/projects/CLDR/issues/?filter=allissues)

**Comment by nobreferreira** [comment]
Will do. TY

**Comment by nobreferreira** [comment]
https://unicode-org.atlassian.net/browse/CLDR-16093
