### ISSUE TITLE
Numeric type of Intl.DateTimeFormat [[FractionalSecondDigits]]

### ISSUE THREAD

**Issue by ptomato** [tc39/ecma402#725]
(Follow up from https://github.com/tc39/ecma402/pull/715#issuecomment-1300647364)

There is an inconsistency about whether [[FractionalSecondDigits]] contains a Number or mathematical value. [Properties of Intl.DateTimeFormat instances](https://tc39.es/ecma402/#sec-properties-of-intl-datetimeformat-instances) says either undefined or a "positive non-zero integer Number value" but step 36.d of [InitializeDateTimeFormat](https://tc39.es/ecma402/#sec-initializedatetimeformat) arguably stores a mathematical value (returned from GetNumberOption in step 36.b.i) in the slot. In [FormatDateTimePattern](https://tc39.es/ecma402/#sec-initializedatetimeformat) the value is passed to CreateDataPropertyOrThrow in step 12.b which suggests a Number value, but in 15.c.ii it's used in a mixed mathematical/Number value calculation which is an editorial error.

(I say "arguably stores a mathematical value" because GetNumberOption/DefaultNumberOption return a Number value, but it is compared against mathematical values _minimum_ and _maximum_, and the operation floor() is applied to it, all of which are only valid for mathematical values.)

**Comment by gibson042** [comment]
Reated: #648

**Comment by anba** [comment]
#822 should fix this issue.

**Comment by sffc** [comment]
#822 is merged so I assume this issue is fixed. If it is not fixed, please re-open.
