### ISSUE TITLE
Int.NumberFormat could return "-0"

### ISSUE THREAD

**Issue by chapman-cc** [tc39/ecma402#748]
I am finding a strange behaviour for `Intl.NumberFormat` _(decimal)_

let's say I have a helper function to format a number without decimal
```
const noDigit = new Intl.NumberFormat("en", {style: "decimal", maximumFractionDigits: 0})
noDigit.format(-0.1)    // "-1" , correct result
noDigit.format(-0.4)    // "-0", incorrect result
```

the problem is zero should not be negative (hyphen prefix)
is this a bug or what?

**Comment by sffc** [comment]
This is expected behavior; if you don't want the negative zero, you can use `signDisplay: "negative"` in the constructor in browsers that support Intl.NumberFormat v3.
