### ISSUE TITLE
missing [[RangePatterns]] in Intl.DateTimeFormat  ?

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#762]
I am not sure this is a bug or not. Currently the step 2 of

https://tc39.es/ecma402/#sec-intl.datetimeformat

Let dateTimeFormat be ? [OrdinaryCreateFromConstructor](https://tc39.es/ecma262/#sec-ordinarycreatefromconstructor)(newTarget, "%DateTimeFormat.prototype%", « [[InitializedDateTimeFormat]], [[Locale]], [[Calendar]], [[NumberingSystem]], [[TimeZone]], [[Weekday]], [[Era]], [[Year]], [[Month]], [[Day]], [[DayPeriod]], [[Hour]], [[Minute]], [[Second]], [[FractionalSecondDigits]], [[TimeZoneName]], [[HourCycle]], [[Pattern]], [[BoundFormat]] »).

but I see [[RangePatterns]] is not listed here. Should we add [[RangePattern]] here?

@sffc @gibson042

**Comment by sffc** [comment]
Yeah I think this is a bug because it is a slot just like `[[Pattern]]`
