### ISSUE TITLE
Wrong currency for CAD currency code in fr-ca

### ISSUE THREAD

**Issue by Acemanu412** [tc39/ecma402#794]
Hello folks,

Currently, the fr-ca locale displays "CAD" as "$" which is incorrect. My understanding is that the correct code there is "$ CA".

Thank you!

**Comment by ljharb** [comment]
Presumably this is in a specific browser?

**Comment by anba** [comment]
This is intentional per <https://unicode-org.atlassian.net/browse/CLDR-14862>.

**Comment by sffc** [comment]
Closing according to @anba's comment that this is expected in CLDR data. The place to appeal to would be CLDR.
