### ISSUE TITLE
Use unicode_script_subtag and unicode_region_subtag in Locale.prototype.{script,region}

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#799]
The current definition is hard to read and at least for `Intl.Locale.prototype.script` also incorrect.

[get Intl.Locale.prototype.script](https://tc39.es/ecma402/#sec-Intl.Locale.prototype.script)
> 5. Let lang be the longest prefix of locale matched by the unicode_language_id [Unicode locale nonterminal](https://tc39.es/ecma402/#sec-language-tags).
> 6. If lang contains a [subtag](https://tc39.es/ecma402/#bcp-47-subtag) of length 4, return that [subtag](https://tc39.es/ecma402/#bcp-47-subtag).

`new Intl.Locale("de-1996").script` should return the variant subtag `"1996"` according to that definition, which is clearly wrong.

**Comment by gibson042** [comment]
Nice catch! I submitted a fix at #801.
