### ISSUE TITLE
Canonicalization for Calendar identifiers?

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#828]
Previously reported at tc39/proposal-temporal#2314, but that issue was closed after the case-normalisation part was fixed. 

Q: Should `new Temporal.Calendar("islamicc").id` return `"islamicc"` or the canonical identifier `"islamic-civil"`?

If no canonicalisation should happen, it'd be good to mention this in <https://tc39.es/proposal-temporal/#sec-calendar-types>.

**Comment by justingrant** [comment]
Temporal meeting 2023-08-17:
* Per @sffc, we'll transfer this issue to the 402 repo. TG2 should decide whether a normative PR is needed. 
* If we want to match time zone behavior, then DTF.resolvedOptions() should retain current behavior, but testing for equality (e.g. among Temporal.PlainDate instances with "islamicc" or the canonical identifier "islamic-civil") should canonicalize first before comparing for equality.
* There's also the cases of "gregorian" and "ethiopic-ahmete-alem" where those aliases are accepted in CLDR but they are resolved to the canonical IDs "gregory" and "ethioaa", respectively.  Should behavior be consistent for these vs. "islamicc" ?
* UTS 35 explains the difference between "preferred" (like islamicc) and "alias" (like "gregorian" and "ethiopic-ahmete-alem").

**Comment by anba** [comment]
- `gregorian` isn't a valid BCP47 identifier and therefore shouldn't be allowed in `Temporal.Calendar`. 
- `ethiopic-amete-alem` is a special case -> #285

**Comment by anba** [comment]
The Temporal implementation for SpiderMonkey will canonicalise the calendar identifier. Anything else will be too confusing. For example without canonicalisation this snippet will throw a RangeError:
```js
let date = new Temporal.PlainDate(2000, 1, 1, "islamicc");
date.toLocaleString("en", {calendar: "islamicc"});
```

No use cases have been presented where non-canonical calendar identifier are useful or needed and unconditionally applying canonicalisation matches the behaviour for all `Intl` objects, so `Temporal` should follow suit.

**Comment by ptomato** [comment]
Note that I previously thought this was undetermined for Intl.DateTimeFormat, but Anba actually fixed it already in https://github.com/tc39/ecma402/pull/418 several years ago. We've updated Temporal to match 402 and I will include a test for Intl.DateTimeFormat in the corresponding test262 tests.
