### ISSUE TITLE
Default of ignorePunctuation need to be locale dependent

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/ecma402#832]
Currently, in the ECMA402 spec, the default of the ignorePunctuation is always false for Intl.Collator
https://tc39.es/ecma402/#sec-initializecollator
```
29. Let ignorePunctuation be ? [GetOption](https://tc39.es/ecma402/#sec-getoption)(options, "ignorePunctuation", boolean, empty, false).
30. Set collator.[[IgnorePunctuation]] to ignorePunctuation.
```
This work for most, except "th", locale which the default is true

https://github.com/unicode-org/cldr/blob/02a4b1c580095e226805fb3faf4de203074148df/common/collation/th.xml#L17
```
				[alternate shifted]
```
https://unicode.org/reports/tr35/tr35-collation.html#non_variable_symbols
https://unicode.org/reports/tr35/tr35-collation.html#Collation_Settings

ICU also use UCOL_NON_IGNORABLE as default if the rule does not specify the value, but in "th" locale, the above rule will make it default to UCOL_SHIFTED
https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/ucol_8h.html#a583fbe7fc4a850e2fcc692e766d2826c

 enum |  description
-- | --
UCOL_ALTERNATE_HANDLING | Attribute for handling variable elements.Acceptable values are UCOL_NON_IGNORABLE (default) which treats all the codepoints with non-ignorable primary weights in the same way, and UCOL_SHIFTED which causes codepoints with primary weights that are equal or below the variable top value to be ignored on primary level and moved to the quaternary level.Stable:ICU 2.0

The above documentation is not truely accurate because that is the default for the class itself if the rule does not include alternate. But since the rule for "th" include alternate, the default for the collator object of thai locale is not UCOL_NON_IGNORABLE but UCOL_SHIFTED. 
So we really have two different level of default in ICU. The default for the code without locale data , and the default of the object created by locale data . The first one is always UCOL_NON_IGNORABLE as the document states, but the second one is changed by the value inside the locale rule and therefore the object default for 'th' locale is actually UCOL_SHIFTED. 

consider the following code
```
let th = new Intl.Collator("th")
let en = new Intl.Collator("en")
th.resolvedOptions().ignorePunctuation
en.resolvedOptions().ignorePunctuation
th.compare("", " ")
th.compare("", "*")
en.compare("", " ")
en.compare("", "*")
```
According to the current spec text, the output should be

```
false
false
-1
-1
-1
-1
```
Currently, v8 (Version 117.0.5938.48 (Official Build) (x86_64)) violate the specification and not use false as default for the case of "th" but a default value from the locale data
so the result are 
```
true
false
0
0
-1
-1
```
But this should be desire behavior because according to the th rule in CLDR data, the default for the th should be true.

In Safari (Version 16.6 (18615.3.12.11.2)) and FireFox (117.0 (64-bit))  the results are
```
false
false
0
0
-1
-1
```
This mean the implementation still consider shift for Thai while implement the 10.3.3.2 CompareStrings ( collator, x, y ) but the resolvedOption strictly follow the spec text and use false for the default for "th"

V8 has other problem. the implementation currently incorrectly ignore  {ignorePunctuation: false}  . This is not a problem in all other locales since all other locales the default is false, but for "th" locale, this does not work. 
 
@anba @gibson042 @sffc

**Comment by FrankYFTang** [comment]
See downstream issues (two different one, one block by this , the other not)
block by this https://bugs.chromium.org/p/v8/issues/detail?id=13204 
not block by this  https://bugs.chromium.org/p/v8/issues/detail?id=14307

**Comment by FrankYFTang** [comment]
documentation bug file against ICU https://unicode-org.atlassian.net/browse/ICU-22489

**Comment by anba** [comment]
SpiderMonkey, and I guess also JSC, map `ignorePunctuation = false` to `UCOL_DEFAULT` instead of `UCOL_NON_IGNORABLE`. This should explain why the `Intl.Collator.prototype.compare` call returns the default value for Thai (i.e. `UCOL_SHIFTED`).

(The resolved options value isn't read from the underlying `UCollator`, but instead saved separately. So we don't use `ucol_getAttribute(coll, UCOL_ALTERNATE_HANDLING, &err)` to retrieve the collator options when computing the result for `Intl.Collator.prototype.resolvedOptions()`.)

**Comment by ben-allen** [comment]
Closed as fixed by https://github.com/tc39/ecma402/pull/833
