### ISSUE TITLE
Displaying wrong date format for sr-Latn-me locale

### ISSUE THREAD

**Issue by hakastein** [tc39/ecma402#838]
The following code produces wrong date format

```js
const date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));

console.log(new Intl.DateTimeFormat("sr-Latn-me").format(date)); // 20. 12. 2012.
```

This is should return 20.12.2012.

Resources:
* wiki: https://en.wikipedia.org/wiki/Date_format_by_country
* Unicode CLDR: https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-dates-modern/main/sr-Latn-ME/ca-generic.json#L309

**Comment by anba** [comment]
The linked CLDR resource file is for the "generic" calendar, but the test case uses the Gregorian calendar (, which is the default calendar for the locale `sr-Latn-ME`), so the correct resource is actually <https://github.com/unicode-org/cldr-json/blob/a2d301b19caf43bf548ce1eb25bfc8ce8fc04feb/cldr-json/cldr-dates-modern/main/sr-Latn-ME/ca-gregorian.json#L384>, which contains the relevant entry:
> "yMd": "d. M. y."

**Comment by sffc** [comment]
Thanks @anba for the investigation. Closing as WAI.

@hakastein If you feel the value for sr-Latn-ME in CLDR is erroneous, please file an issue against CLDR:

https://unicode-org.atlassian.net/jira
