### ISSUE TITLE
Intl.NumberFormat with style: 'decimal' if the number has four digits, does not add the point on locale spanish

### ISSUE THREAD

**Issue by Negri234279** [tc39/ecma402#841]
Intl.NumberFormat with style: 'decimal' if the number has four digits, does not add the period only if it has five or more digits but only in locale on 'es-ES', with en-EN works

```js
const formatNumber = new Intl.NumberFormat('es-ES', {
  style: 'decimal',
})

formatNumber.format(1234.56)

Expected: 1.234.56
Reality: 1234.56

Expected: 1.234
Reality: 1234
```

**Comment by sffc** [comment]
This comes from CLDR. There is an upstream issue about it: https://unicode-org.atlassian.net/browse/CLDR-13265
