### ISSUE TITLE
Need support for nigerian currency.

### ISSUE THREAD

**Issue by HarshikaSM** [tc39/ecma402#844]
For nigerian currency, the currency code is getting displayed instead of the currency symbol along with the value. 
Also created another example for reference: https://codepen.io/HarshikaSM/pen/wvNxgVK

I had raised the same feature request on the vue-currency-input repo, but as per the discussion over there, it seems the issue is with the number formatting

[https://github.com/dm4t2/vue-currency-input/discussions/408]

**Comment by anba** [comment]
```js
new Intl.NumberFormat("yo-NG", {style:"currency", currency: "NGN"}).format(11)
```

Returns `"₦11.00"` in Safari and Firefox, but `"11,00 NGN"` in Chrome. Therefore this issue should be reported to <https://bugs.chromium.org/p/chromium/issues/list>.

**Comment by sffc** [comment]
@FrankYFTang FYI, possible bug in Chrome, maybe data slicing.

Closing the issue since it is out of scope of ECMA-402.

**Comment by HarshikaSM** [comment]
Thanks, reported the issue further.
