### ISSUE TITLE
Intl API for parsing locale aware strings

### ISSUE THREAD

**Issue by JeremiePat** [tc39/ecma402#850]
The Intl API is a fundamental API to format some values to a local aware string. Unfortunatly, it is missing an API to do the opposite operation : parsing strings to get a value. Currently, only `Intl.segmenter` is available to properly split out a string based on its locale format. It would be a huge enhancement to have some locale aware parser, for, at least, numbers and date.

Parsing locale aware strings is complicated and would benefits from a native support.

## Date & Time

Currently, `Date.parse` and the future `Temporal.*.from` are not locale aware (and very likely will never be)

It would be a bliss to have somethind along this line: 

```js
const frenchDateParser = new Intl.DateTimeParser('fr') // very likely with some options when ambiguity needs to be handled.

const dateA = frenchDateParser.parse('12/01/2024') // Provide a Date or Temporal object for December 1st, 2024 (not January 12th, 2024)
const dateB = frenchDateParser.parse('Lundi 8 Janvier 2024') // Provide a Date or Temporal object for January 8th, 2024
const timeA = frenchDateParser.parse('Le 8 janvier 2024 à 17h') // Provide a Date or Temporal object for January 8th, 2024 at 5pm
const timeB = frenchDateParser.parse('18h34') // Provide a Date or Temporal object for the time 6:34pm
```

Some libraries offer some solutions: 
- [Moment](https://momentjs.com/docs/#/parsing/string-format/) (with explicit parsing format)
- [Luxon](https://moment.github.io/luxon/#/parsing) (for some machine/normative formats)
- [DayJS](https://day.js.org/docs/en/parse/string-format) (with explicit parsing format)
- [Chrono](https://github.com/wanasit/chrono?tab=readme-ov-file#locales)
- [any-date-parser](https://github.com/kensnyder/any-date-parser?tab=readme-ov-file#locale-support)

## Numbers

Currently JS doesn't have a native way to parse a locale formated number such as `"10 345,56"` (`10345.56` in _fr-fr_ locale) or `"12,340"` (`12340` in _en-us_ or `12.34` in _fr-fr_. Currencies are also tricky as some locales use the symbol as prefix (`"$24.35"`) and others as suffix (`"24,35 €"`) 

Having a parser like that would be quite usefull:

```js
const usCurrencyParser = new Intl.NumberParser('en-us', { style: "currency", currency: 'USD' }) // options should be very similar to the one used by NumberFormat

const numA = usCurrencyParser.parse('$24.40') // 24.4
const numB = usCurrencyParser.parse('34,67 €') // NaN ?
```

Some libraries offer some solutions:
- [Numeral](http://numeraljs.com/) (not locale aware but very versatile)
- [BrighSpacetUI](https://github.com/BrightspaceUI/intl?tab=readme-ov-file#number-parsing) (provide also parsing for date and time)

**Comment by sffc** [comment]
Hello! Please read issue #1 for why we don't support localized string parsing in Intl.

**Comment by sffc** [comment]
> It would be a huge enhancement to have some locale aware parser, for, at least, numbers and date.

Please also read my blog post on why localized date parsing is probably the wrong solution to begin with: https://blog.sffc.xyz/post/190943794505/why-you-should-not-parse-localized-strings

If you can articulate an additional use case beyond what's listed above, I'm happy to hear and integrate it.
