### ISSUE TITLE
How to use ecma402 Intl.GetCanonicalLocales in Android

### ISSUE THREAD

**Issue by jayykumar** [tc39/ecma402#857]
I compiled code using npm run build in windows, I then copied  ecmarkup.js and ecmarkup.css that are generated into Android App

I m trying these library and get device locale by following code in Android (Pixel 6) device

Intl.getCanonicalLocales('EN-US'); 

It shows following errors, Refer attached screenshot. 
Cannot read properties of null (reading 'addEventListener') 
Cannot read properties of undefined (reading '$specContainer')

<img width="775" alt="Screenshot 2024-02-06 at 4 47 31 PM" src="https://github.com/tc39/ecma402/assets/63598833/94b20424-6f17-4955-955d-ed0d1627de29">

I do not have nodeJS in android application. is it required to have nodejs ? or I have to follow different build process for Android devices. current Android Version 14

**Comment by sffc** [comment]
Hi! You shouldn't need ecmarkup.js if your goal is to use this Intl API on Android. It looks like your error is coming from ecmarkup.js, so I would encourage you to file the bug on that repository (https://github.com/tc39/ecmarkup).
