### ISSUE TITLE
Intl.DateTimeFormat should localize era names as well

### ISSUE THREAD

**Issue by watilde** [tc39/ecma402#88]
In [annex-implementation-dependent-behaviour](https://tc39.github.io/ecma402/#annex-implementation-dependent-behaviour), it is mentioned that `DateTimeFormat` should localize era names: [annexes.html#L102](https://github.com/tc39/ecma402/blob/a47b02e1b1b83c2df4e33925d372fc68bb84219d/spec/annexes.html#L102), but in the part of [12.1.6FormatDateTime](https://tc39.github.io/ecma402/#sec-formatdatetime) linked from the above, there is no description about the localized era names. Probably it can be bug.

The description to resolve it may can be like this:
```
If _p_ is *"era"*, then the String value may also depend on whether _dateTimeFormat_ has a [[era]] internal slot
```

Related links: https://github.com/andyearnshaw/Intl.js/issues/164, https://github.com/andyearnshaw/Intl.js/pull/166

Thanks.

**Comment by caridy** [comment]
merged as b0c9b6bd834780b74d4efe9448a16f19bcbc590b

**Comment by littledan** [comment]
Did we get any implementations of this, besides Intl.js? Are there any tests in test262?

**Comment by jungshik** [comment]
Era is localized in v8, I  believe because cldr has data for them.
