### ISSUE TITLE
Decimal & Intl topic for the July Ecma 402 monthly call

### ISSUE THREAD

**Issue by jessealama** [tc39/ecma402#906]
Decimal and Intl should be together! Here's a [current PR](https://github.com/tc39/proposal-decimal/pull/163) in the proposal-decimal repo that I'd like to briefly discuss at the next 402 monthly call, if there's time and interest. The intention is to find out whether I'm barking up the right tree, and if not, I'd request a hint or two for how to get the integration right.

**Comment by jessealama** [comment]
We discussed this. Thanks for adding it to the agenda!

**Comment by sffc** [comment]
2024-07-18 TG2 notes: https://github.com/tc39/ecma402/blob/main/meetings/notes-2024-07-18.md#decimal--intl-topic-for-the-july-ecma-402-monthly-call
