### ISSUE TITLE
Make ILD a well-defined term in the spec and use it more consistently

### ISSUE THREAD

**Issue by sffc** [tc39/ecma402#909]
Currently the term "ILD" is defined and re-defined multiple times, and sometimes it is "ILND". We also don't consistently use it everywhere there is ILD behavior: for example, the spec sometimes says "with values based on locale".

We should clean this up to use ILD consistently everywhere.

CC @gibson042 @ben-allen

**Comment by anba** [comment]
ILND = **I**mplementation-, **L**ocale-, and **N**umbering system-**D**ependent.
ILD = **I**mplementation- and **L**ocale-**D**ependent.

Note 1 below <https://tc39.es/ecma402/#table-numbering-system-digits>:
> The computations rely on String values and locations within numeric strings that are dependent upon the implementation and the effective locale of numberFormat ("ILD") or upon the implementation, the effective locale, and the numbering system of numberFormat ("ILND"). [...]

**Comment by gibson042** [comment]
Fixed by #924
