### ISSUE TITLE
Currency-derived fractional digit count defaults are inappropriately applied with scientific/engineering/etc. `notation`

### ISSUE THREAD

**Issue by gibson042** [tc39/ecma402#912]
_(originally posted by @gibson042 in https://github.com/tc39/ecma402/pull/839#discussion_r1370737507 )_

We arguably have a bug where currency-derived fractional digit count defaults are applied even when the decimal point is moved away from its absolute position, as in `new Intl.NumberFormat("en", { style: "currency", currency, currencyDisplay: "code", notation: "engineering" }).format(12345).replace(/^.*\s/, "")` resulting in "12E3" for JPY but "12.35E3" for USD).

Put another way, I think I expect currency-derived precision and corresponding rounding to apply only when `notation` is "standard" (i.e., not even when the decimal point _happens_ to be in the right place with scientific/engineering/compact notation).

**Comment by ray007** [comment]
Currency formatting with engineering notation, is that a real-world issue?

**Comment by sffc** [comment]
I would support a PR tweaking this behavior.
