### ISSUE TITLE
Unexpect return value from Date.toLocaleString for some locales

### ISSUE THREAD

**Issue by ishando** [tc39/ecma402#927]
**Description:** 
using toLocaleString(loc, { month: '2-digit' }) I would expect to always get a 2 character returned string

**Output:**

```
d = new Date
console.log(d.toLocaleString('nb-NO', { month: '2-digit' })
> 09.
console.log(d.toLocaleString('nb-NO', { date: '2-digit' })
> 24.

console.log(d.toLocaleString('en', { month: '2-digit' })
> 09
console.log(d.toLocaleString('en', { date: '2-digit' })
> 24
```

Haven't tested if there are other locales similarly affected

**Comment by sffc** [comment]
"2-digit" gives a hint that you would like the _month field_ to be 2 digits. Locales are allowed to add additional context or not use a 2-digit format at all if it doesn't make sense in their calendar system. So it looks like this is working as intended.
