### ISSUE TITLE
Intl.NumberFormat.formatRange seems to missing the `Range Pattern Processing` step compared to LDML

### ISSUE THREAD

**Issue by longlho** [tc39/ecma402#935]
I know we're not strictly following LDML, but here me out:
Here in https://tc39.es/ecma402/#sec-partitionnumberrangepattern the last step is `CollapseNumberRange` which is implementation-dependent. It generally removes common tokens and adjust plural ranges. However, after collapsing, LDML selectively inserts `White_Space` based on certain heuristics but ECMA402 does not. Without this step there's no room in the spec to deal with whitespace, since range separator is a constant (so it's either `-`, no space or ` - `, with space, for example).
In my attempt to polyfill `CollapseNumberRange` it's just impossible to make it close to web reality without this step and following the spec somewhat strictly.
An option is I can technically munge whitespace insertion into `CollapseNumberRange` but that seems pretty wrong.
Am I missing something @sffc ?

**Comment by ben-allen** [comment]
My knee-jerk sense is that it does naturally fit into `CollapseNumberRange`, but I'm not as familiar with the implementation side as I could be. I'm talking with other Igalians about it today. Do you have a good example of a case where the whitespace problems related to `Range Pattern Processing` are occurring? 

Additionally: is the whitespace problems separate from the isssue with duplicate/uncollapsed currency symbols from the [formatjs](https://github.com/formatjs/formatjs/issues/4521) issue? I may be misunderstanding something fundamental here.

**Comment by anba** [comment]
I think at least `numberFormat` should be passed to `CollapseNumberRange` to enable locale-specific modifications of the `result` List.

**Comment by longlho** [comment]
@ben-allen so it's related and I'm trying to fix this. As part of the fix I found out about this missing step.
I don't know if it should be part of collapse tbh since it's technically "expanding" :)

**Comment by ben-allen** [comment]
A semi-silly thought: is it possible to spin the `White_Space` insertion as a necessary part of removing the unwanted currency symbols -- "collapse, but not so much!" -- rather than an expansion? 

Semi-silly thoughts aside, what do you think of anba's suggestion? The addition of the `numberFormat` parameter could come alongside a note (or maybe even normative text) on the whitespace insertion heuristic from LDML's `Range Pattern Processing`.

**Comment by longlho** [comment]
So the [Range Pattern Processing](https://unicode-org.github.io/cldr/ldml/tr35-numbers.html#range-pattern-processing) happens post collapsing and depending on the prefix/suffix char to the range separator, a white space maybe inserted. In ECMA402 it says collapsing can `removing redundant information and resolving internal inconsistency`. I guess the `resolving internal inconsistency` part can account for whitespace. Overall it's a bit vague so I mostly need confirmation.
And yeah as @anba mentioned it should take in `numberFormat` itself IMO.

**Comment by sffc** [comment]
Yeah, it's probably worth a PR explicitly stating in this extremely hand-wavy AO that characters can also be added and replaced. I don't think any locale currently does this, but the AO should also support cases such as "USD 3-USD 5" turning to "USD 3 - $5".
