### ISSUE TITLE
Incorrect Currency Format for Mongolian Tugrik (MNT) in Intl.NumberFormat

### ISSUE THREAD

**Issue by zolzaya** [tc39/ecma402#937]
I’m experiencing an issue with the Intl.NumberFormat API when formatting Mongolian Tugrik (MNT) currency. Currently, `Intl.NumberFormat` displays the currency as MNT 12,000, which is not the standard format used in Mongolia. The correct format should be 12,000 ₮, with the currency symbol ₮ placed after the amount and without the currency code “MNT”.

**Steps to Reproduce:**
```
const amount = 12000;
const formattedAmount = new Intl.NumberFormat('mn-MN', {
    style: 'currency',
    currency: 'MNT',
}).format(amount);

console.log(formattedAmount); // Output: MNT 12,000
// Expected Output: 12,000 ₮
```

**Expected Outcome:**
The formatted currency output should match the standard Mongolian format, displaying the amount followed by the symbol ₮ (e.g., 12,000 ₮), without the currency code.

**Actual Outcome:**
The output currently displays as MNT 12,000, which does not align with local standards.

**Additional Information:**
It appears that `Intl.NumberFormat` is using the currency code “MNT” instead of the localized symbol ₮. This could be due to incorrect data in the underlying CLDR or ICU libraries used by Intl.

**Comment by anba** [comment]
This is a Chromium-only issue and should be reported to <https://issues.chromium.org>. 

Chromium strips some locale data to reduce the binary size, which can lead to issues like this one. Firefox and Safari both return `"₮ 12,000.00"`.
