### ISSUE TITLE
Can `numberFormat.[[NumberingSystem]]` be null?

### ISSUE THREAD

**Issue by GPHemsley** [tc39/ecma402#944]
Am I correct in my reading of [`Intl.NumberFormat()`](https://tc39.es/ecma402/#sec-intl.numberformat) that `numberFormat.[[NumberingSystem]]` may technically sometimes be null? What about undefined?

It seems difficult to replicate in practice, because fallback locales typically have default numbering systems.

**Comment by sffc** [comment]
It would be reasonable for us to change the spec to make it non-null/non-undefined if the spec does not already require that.

**Comment by anba** [comment]
All extension key values are non-empty String values per <https://tc39.es/ecma402/#sec-internal-slots>. (With the exception of `[[co]]`, cf. <https://tc39.es/ecma402/#sec-intl-collator-internal-slots>.)

**Comment by ben-allen** [comment]
Close as question answered -- the value of the `[[NumberingSystem]]` slot cannot be null.
