### ISSUE TITLE
[editorial] incorrect usage of array in spec text

### ISSUE THREAD

**Issue by caridy** [tc39/ecma402#97]
![image](https://cloud.githubusercontent.com/assets/38969/17194990/1f22cf2a-5410-11e6-9a52-13e961cc86ec.png)

**Comment by caridy** [comment]
https://tc39.github.io/ecma402/#sec-partitionnumberpattern, specifically, `digits[digit]`. I will take care of it.

**Comment by anba** [comment]
#158 should fix this issue (it replaces all internal objects and arrays with records resp. lists).

**Comment by caridy** [comment]
fixed by #158
